\RequirePackage{rotating}
\documentclass[man,floatsintext,a4paper,biblatex]{apa6}
\usepackage[english, british]{babel}
\usepackage[style=apa,sortcites=true,sorting=nyt,backend=biber]{biblatex}
\DeclareLanguageMapping{british}{british-apa}
% http://tex.stackexchange.com/questions/162212/initials-in-the-bibliography-firstinits-uniquename-not-working-correctly-in-bib
\DeclareSourcemap{
  \maps[datatype=bibtex]{
    \map{
       \step[fieldsource=sortname]
       \step[fieldset=namea, origfieldval, final]
    }
  }
}
\DeclareLabelname{
  \field{namea}
  \field{shortauthor}
  \field{author}
  \field{shorteditor}
  \field{editor}
  \field{translator}
}
\addbibresource{bibliography.bib}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage{amssymb,amsfonts,textcomp}
\usepackage{array}
\usepackage{hhline}
\usepackage{graphicx}
\usepackage[page,header]{appendix}
\usepackage{titletoc}
\usepackage{lipsum}

\usepackage[]{hyperref}
\hypersetup{
    bookmarksnumbered=true,     
    bookmarksopen=true,         
    bookmarksopenlevel=1,       
    colorlinks=true,            
    allcolors=blue,
    pdfstartview=Fit,           
    pdfpagemode=UseOutlines,    % this is the option you were lookin for
    pdfpagelayout=TwoPageRight
}
\usepackage{cleveref}
\usepackage[table]{xcolor}
\usepackage[textwidth=2cm,color=green,textsize=tiny]{todonotes}
\reversemarginpar
\usepackage{afterpage}
\makeatletter
\newcommand\arraybslash{\let\\\@arraycr}
\makeatother
\setlength\tabcolsep{1mm}
\renewcommand\arraystretch{1.3}
\newcounter{Figure}
\renewcommand\theFigure{\arabic{Figure}}

%\fancyhead{}
%\fancyfoot{}
\renewcommand{\headrulewidth}{0pt}
%\fancyhead[RO,LE]{\footnotesize\thepage}
\fancyhead[CO,CE]{\footnotesize EFFECTS OF ABM ON RUMINATION AND WORRY ABOUT CURRENT CONCERNS}
%\fancyhead[RE]{\footnotesize\slshape\leftmark}
%\pagestyle{fancy}

\title{The effects of attentional bias modification on rumination and worry about current concerns: a case-series}
\shorttitle{}
\author{Paul Sharpe}
\affiliation{University of Exeter}
\leftheader{Attentional bias modification of rumination towards a self-relevant goal: A case-series}

\abstract{Rumination and worry are thinking styles closely associated with
depression and anxiety. There is evidence suggesting that an attentional
bias towards negative stimuli plays a role in these associations. A
hypothesis arising from the attentional bias literature is that depressive
rumination results from an impaired ability to disengage attention from
negative thoughts, and that reducing this bias will reduce rumination
and depressive symptoms. The goal progress theory of rumination proposes
that rumination results when from discrepancies between perceived and
expected progress towards a goal. Current concerns are mental states
representative of such goal progress discrepancies. The current study
tests the disengagement hypothesis by aiming to reduce attentional bias
to towards negative words and words associated with an unresolved current
concern, and measuring the effects on rumination, worry, mood and symptoms
of anxiety and depression. Participants were 12 (10 female) university
students or staff scoring low for depression but high for trait rumination
and/or trait worry. This was a non-concurrent, multiple baseline
case-series replication in which each participant completed between
25--35 sessions, a minimum of 8 including ABM training. Participants
ran dot-probe tasks on their own computers designed to first measure,
then modify attentional bias towards a general set of negative words and
words associated with a current concern of their choosing. There were
no significant post-training effects on trait rumination, trait worry,
depression and anxiety. Randomisation tests showed a significant reduction
in attentional bias towards negative words, but no post ABM differences
in attentional bias towards current concern words, rumination towards
the concern itself, positive affect, negative affect or depression.}

\authornote{I certify that all material in this dissertation \textbf{which
is not my own work} has been identified with appropriate acknowledgement
and referencing and I also certify that no material is included for
which a degree has previously been conferred upon me.}

% http://tex.stackexchange.com/questions/35532/using-newcommand-in-includegraphics-option-to-substitute-graphic-sizes
\makeatletter
\define@key{Gin}{plotwh}[true]{%
    \edef\@tempa{{Gin}{width=90mm,height=70mm}}%
    \expandafter\setkeys\@tempa
}
\makeatother

\usepackage{amsmath,siunitx,caption}
\newcommand{\IE}[1][1]{% indent entry
  \hspace{#1em}\ignorespaces
}
\usepackage{mathtools}
\usepackage{csvsimple}

\usepackage{pifont}
\usepackage{booktabs}
\newcommand*\rot{\rotatebox{90}}

\usepackage{tabularx}
\usepackage{tikz}
\newcommand\strokeA{\tikz[baseline=-.5ex]{ \draw[black,thick,align=center] (0,0) -- (2ex,0); }}
\newcommand\strokeB{\tikz[baseline=-.5ex]{ \draw[red,thick,dotted] (0,0) -- (2ex,0); }}
\newcommand\strokeC{\tikz[baseline=-.5ex]{ \draw[black,thick,dotted] (0,0) -- (2ex,0); }}

\usepackage{subcaption}

\begin{document}\thispagestyle{empty}
\setlength{\marginparwidth}{1cm}
%\todototoc
%\listoftodos[Todo list]
\maketitle
\pdfbookmark{\contentsname}{toc}
%\tableofcontents
\startcontents[sections]
\printcontents[sections]{l}{1}{\setcounter{tocdepth}{2}}
\newpage
%\clearpage\setcounter{page}{1}

\section{Introduction}
\label{sec:introduction}

Mixed depression and anxiety is a major public health challenge,
reported as being present in 9.0\% of English adults in the most
household survey \parencite{mcmanus_adult_2009}. Whilst this
reflects a level of stability in prevalence over the preceding
7 years, \textcite{mathers_projections_2006} project that in
2030, unipolar depression will be the 2nd most common cause of
disability-adjusted life years (DALY). Based on 2007 prevalence rates,
\textcite{mccrone_paying_2008} estimate that the combined cost of
depression and anxiety services in England in 2026 will be \pounds5
billion, with lost employment bringing the total cost to \pounds26.4
billion. To address these issues, \textcite{mccrone_paying_2008}
recommend expanding provision of evidence-based interventions in
primary care settings with a focus on the most cost-effective means
of delivery, such as Internet delivered cognitive behavioural therapy
(I-CBT).

Despite their strong evidence-base, pharmacological and psychological
treatments are only partially effective. Combinations of these
treatments are effective at treating depression in about 33\%  of
cases \parencite{andrews_utilising_2004}, and CBT, the gold standard
psychological treatments, has response rates of 50\% or less for
treating anxiety disorders \parencite{schneider_state_2015}. There
is some evidence that the efficacy of CBT for treating depression
is falling \parencite{johnsen_effects_2015}, and the high costs
associated with delivering psychological therapies mean that
waiting times in Britain currently average six to nine months
\parencite{haliwell_fundamental_2007}. Technological advances
may improve cost-effective treatment delivery. I-CBT is a viable
treatment for adults with depression and some anxiety disorders
\parencite{arnberg_internetdelivered_2014}, and mobile apps including
real-time monitoring of mood and behaviour could also contribute
\parencite{cuijpers_psychotherapies_2015}. More research is required
to ascertain whether this potential can be realised in practice.
An expanded understanding of the role played by cognitive mechanisms
such as attention and memory in mood disorders is reflected in the
greater precision of newer treatments. For example, Mindfulness Based
Cognitive Therapy (MBCT) is a treatment which specifically targets
depressive relapse \parencite{segal_mindfulnessbased_2012}, which is
common and becomes increasingly likely with each depressive episode
\parencite{haliwell_fundamental_2007}. The most effective new treatments
for depression and anxiety are likely to draw on evidence which explicates
the role that cognitive mechanisms play in these common disorders,
and computer tasks offer one cost-effective means of delivery.

Rumination is a thinking style closely associated with depression
and anxiety. A more precise definition distinguishes constructive
repetitive thought which support planning, problem solving,
and healthy self-reflection, from extensive evidence linking
unconstructive repetitive thought with psychological distress
and physical health difficulties characteristic of depression
and anxiety \parencite{watkins_constructive_2008}. Although
rumination as a construct is robust, the ten models and five
measures reviewed by \textcite{smith_roadmap_2009} demonstrate
that ``there is no unified definition [...] or standard way of
measuring it'' \textcite[][p. 117]{smith_roadmap_2009}. Response
styles theory \parencite[RST; ][]{nolen-hoeksema_responses_1991}
has been influential in terms of explaining, measuring and treating
depressive rumination. RST considers rumination to be a particular
response to depressed mood where a person tends to focus on
``causes, consequences and symptoms of one's negative affect''
\parencite[][p. 117]{smith_roadmap_2009} thereby prolonging low
mood and depressive episodes. A significant output from RST is the
Ruminative Responses Scale (RRS) \parencite{treynor_rumination_2003},
considered to be the gold standard trait measure of rumination, with
sub scales which can distinguish maladaptive rumination in the form of
'depressive brooding' from the more adaptive 'reflective pondering'. In
support of RST, positive positive distractions have been shown to
significantly reduce depression in dysphoric people over short time
periods \parencite{nolen-hoeksema_rethinking_2008}. However, the temporary
reduction in depressive symptoms provided by distraction suggests a more
enduring underlying link between rumination and depression.

Goal progress theory \parencite{martin_ruminative_1996} is a more general
model which proposes that rumination is initiated by unexpected progress
(more or less) towards a goal\footnote{An extension of the model draws
on parallel distributed processing to explain discrepancies arising
amongst ${concurrent}$ goals \parencite{martin_extending_2006}.}. This account
draws on ideas from control theory \parencite{carver_control_1982}
in that goal discrepancies represent system states outside of
desirable thresholds which cognitive process try to restore
through feedback mechanisms. Rumination is made more likely as a
result of this deployment of attention, memory and consciousness,
and will remain so until goal progress becomes satisfactory,
the goal is perceived as being met or it has been abandoned. For
\textcite[][p. 7]{martin_ruminative_1996}, rumination is "a class of
conscious thoughts that revolve around a common instrumental theme and
that recur in the absence of immediate environmental demands requiring
the thoughts". A closely related concept is the 'current concern',
which \textcite[][p.249]{klinger_motivation_2011} define as \enquote{the
state of an organism between the time it becomes committed to pursuing
a goal and the time it either gains the goal or abandons the pursuit.}
Together, goal progress theory and current concerns provide a framework
for understanding rumination in terms of motivation, cognition and
emotion. Where progress towards resolving a current concern is slower than
expected, priming will potentiate internal and external cues on related
themes to draw attention to the discrepancy. Similarly, negative affect
will draw attention to the unsatisfactory goal progress. This account
explains why targeting underlying goal discrepancies may provide more
long term relief from the negative affect associated with rumination
than distraction interventions.

Worry is a thought process with both similarities and differences to
rumination.  \textcite[][p. 10]{borkovec_preliminary_1983} define worry
as \enquote{a chain of thoughts and images, negatively affect-laden and
relatively uncontrollable}.  Whilst some studies associate depression
with rumination and worry with anxiety, measures of rumination
and worry are closely correlated \parencite{smith_roadmap_2009}.
Temporal distinctions suggest that rumination primarily focuses on
past events, whereas worry tends to focus on events in the future
\parencite{papageorgiou_depressive_2004,watkins_comparisons_2005}.
However, although \textcite{mclaughlin_effects_2007} confirmed this
general distinction, they also found that induced rumination began as
past-focused but then displayed a linear trend towards thoughts about the
present and finally the future. Whilst rumination is linked depression
levels and predicts the onset of depressive episodes, it also predicts
symptoms of anxiety \parencite{nolen-hoeksema_role_2000}. Both forms
of repetitive negative thought regularly occur in the same individual,
which suggests that they may share common underlying processes (at least
in non-clinical populations) \parencite{watkins_comparisons_2005}. This
is consistent with the common co-morbidity of anxiety and depression
\parencite{kessler_impairment_1999}. Studies which have directly compared
rumination and worry support a hypothesis that similar cognitive control
impairments may play \parencite{beckwe_worrying_2014}. In summary,
distinguishing worry from rumination remains problematic.

The mechanisms underlying rumination are less well understood than their
affective consequences \parencite{koster_understanding_2011}. For example,
it remains unclear whether rumination is an automatic or consciously
controlled process \textcite{smith_roadmap_2009}. Nevertheless,
numerous studies indicate that a range of cognitive biases
which are common across anxiety and depression may also play a
role in rumination. These included biases of attention, memory,
interpretation, inhibitory control, emotional associations and
intrusive thoughts \parencite{mathews_cognitive_2005}. Attentional
bias is a disproportionate attentional sensitivity to internal
or external stimuli \parencite{williams_cognitive_1988}. One
unresolved hypothesis is whether depressive rumination is caused,
at least in part, by an impaired ability to disengage attention from
negative thoughts \textcite{koster_understanding_2011}. Disruption
in attention-focusing ability is also a cognitive correlate of worry
\parencite{borkovec_preliminary_1983}. It also remains unclear to
what extent attentional bias results in rumination or rumination
leads to attentional bias \parencite{koster_understanding_2011}.
Whilst \textcite{morrison_role_2008} found a causal relationship
between rumination and positive attentional bias, they did not find the
relationship between rumination and decreased negative bias, which would
be required to support the disengagement hypothesis. Nevertheless, there
is evidence in support of this hypothesis. In a double-blind, randomised
controlled with individuals having mild to severe depressive symptoms,
\textcite{yang_attention_2015} demonstrated that modifying attentional
bias led to reductions in rumination and depressive symptoms, and that
the reductions in depressive symptoms was mediated by rumination

Cognitive bias modification (CBM) techniques have been developed
to change the cognitive biases associated with emotional disorders
\parencite{hertel_cognitive_2011}. This is often achieved using computer
tasks which biases of attention, interpretation or memory. The dot-probe
task \parencite{macleod_attentional_1986} is the gold-standard measure
of attentional bias, using differences in response times to visual
stimuli having differing affective valence, such as negative and neutral
word pairs. Participants respond to a probe which appears at one or
the other location of the previously displayed stimuli. Attentional
bias modification (ABM) manipulates the probe location, to train
attention towards or away from particular stimuli. Numerous studies
have indicated that ABM may be an effective treatment for anxiety
\parencite{hakamata_attention_2010} and more recently ABM has been shown
to reduce depression \parencite{yang_attention_2015}. Critics of CBM
argue that the effect sizes are too small to be clinically relevant
\parencite{cristea_efficacy_2015}. However, advocates argue that
this critique is based on meta-analyses which don't differentiate ABM
from other forms of CBM, which don't focus on a single psychological
dysfunction (anxiety), or analyse studies which demonstrate both
attentional bias change ${and}$ corresponding symptom change. It is
important to note, that in demonstrating the mediating role of rumination
in reducing depressive symptoms, \textcite{yang_attention_2015} met both
of these final criteria.

Most studies which examine rumination towards current concerns have only
been able to measure attentional bias using the emotional Stroop task
\parencite{williams_cognitive_1988}. The current study aims to extend
these findings by using the dot-probe task to measure such attentional
biases, and to then test the effects of ABM training designed to reduce
vigilance towards negative words, and words associated with the current
concern. In other words, the study tests the attentional disengagement
hypothesis \parencite{koster_understanding_2011} in relation to the goal
progress theory of rumination \parencite{martin_ruminative_1996}. This is
a novel test of the potential for ABM training to offer a personalised,
cost-effective treatment for anxiety and depression. Given the various
conceptualisations of rumination, \textcite{smith_roadmap_2009} recommend
using multiple outcome measures. The difficulties in distinguishing
rumination from worry, and the common co-morbidity of anxiety and
depression also suggest multiple measures are appropriate. The current
study measures the effects of ABM on trait and state rumination, trait
worry, mood variables, anxiety and depression. Finally, the study aims to
extend the findings of \textcite{yang_attention_2015} by testing whether
the ABM can reduce rumination and depressive symptoms in a non-clinical
sample. Specific hypotheses were as follows:

\begin{enumerate}
\item Baseline trait rumination, trait anxiety, trait worry and depression 
will differ after ABM training.
\item Attentional bias towards ideographic words associated with a
current concern will differ after ABM training.
\item Attentional bias towards negative words will reduce after ABM training.
\item State measures of rumination, positive affect, negative affect
and depression will change after ABM training.
\end{enumerate}

\section{Method}

\subsection{Design}

The current study included a novel use of ABM training towards an
ideographic current concern, and required a small number of participants
to undertake long-term training. To balance the exploratory nature
of the research with the ability to make statistical inferences
from the results we chose a randomised, single-case series design
\parencite{bulte_r_2008}. In this type of design, a series of baseline
(phase A) measures are compared against those after the (ABM training)
intervention (phase B) \parencite{bulte_r_2008}. The overall design
can be considered a non-concurrent, multiple baseline replication
across participants \parencite{watson_nonconcurrent_1981}. That is
to say, there were multiple participants (case-series), which started
at different times, and the time point of transition to phase B
in each was chosen randomly in advance. Whilst the design lacks a
control condition, it does provide some controls against alternative
explanations of effects. Replication across participants controls for
individual regression to the mean, variable phase A duration controls
for baseline assessment effects, and randomised transition to phase
B controls for extraneous events correlated with phase transition
\parencite{watson_nonconcurrent_1981,watkins_ruminationfocused_2007}.
Furthermore, as this was an exploratory study, limiting Type
I error rates was not a priority. Based on previous research
\parencite{yang_attention_2015}, 8 ABM sessions (phase B) were considered
necessary in order to detect training effects. A total of 35 measurement
times (MTs) were chosen, as (with a minimum of 8 MTs in phases A and B)
the resulting 20 possible transition points allowed significance testing
at the ${p}$=.05 level for each participant completing all sessions
\parencite{onghena_customization_2005,bulte_r_2008}.

\subsection{Participants}

Participants were recruited  using the University of Exeter school of
Psychology research participation system, on-campus posters, departmental
email lists and Facebook groups linked to the University. People
were invited to evaluate a computer-based task with the potential to
reduce rumination towards an unresolved problem of their own choosing.
A maximum payment of {\pounds}20 was offered to participants who completed
all 35 sessions. Participants had to be fluent in English, have normal,
or corrected to normal vision, have access to a home computer running
Windows, Macintosh (OS X 10.9 or later), or Linux operating systems,
and not concurrently undergoing psychotherapy or taking psychotropic
medication.

Screening instruments were created using Lime Survey
\parencite{limesurvey} and completed using a web browser. Inclusion
criteria were a PHQ-8 \parencite{kroenke_phq8_2009} score {\textless}
11, to exclude people with mild depression or above, and, to include
high trait ruminators or trait worriers, a Ruminative Responses Scale
(RRS) \parencite{treynor_rumination_2003} score ${\geq}$ 53 or a Penn
State Worry Questionnaire (PSWQ) \parencite{meyer_development_1990}
score ${\geq}$ 55. The RRS and PSWQ cut points were calculated to place
participants in the top 33\% of these measures, based on a sample
of 210 University of Exeter undergraduate students measured on RRS
(${M}$ = 46.9, ${SD}$ = 12.7) and PSWQ (${M}$ = 48.2, ${SD}$ = 14.9)
\parencite{moberly_controlled_2015}.

<<screening, echo=FALSE, error=TRUE>>=
screening<-read.csv('/media/paul/2E95-1293/study/screening.csv',header=TRUE)
@

Figure \ref{flowchart} summarises the recruitment procedure. Of the
15 people (12 female), who met the screening criteria and offered
to participate, 6 were members of staff, 5 were postgraduate
students, 2 were undergraduate students, 1 was a recent graduate,
and 1 was the partner of an undergraduate student. At screening,
the 15 participants who began the study had a mean PHQ-8
score of \Sexpr{sprintf("%0.2f",mean(screening$phq8total))}
(${SD}$=\Sexpr{sprintf("%0.2f",sd(screening$phq8total))}), a mean
RRS score of \Sexpr{sprintf("%0.2f",mean(screening$rrstotal))}
(${SD}$=\Sexpr{sprintf("%0.2f",sd(screening$rrstotal))}), and a mean
PSWQ score of \Sexpr{sprintf("%0.2f",mean(screening$pswqtotal))}
(${SD}$=\Sexpr{sprintf("%0.2f",sd(screening$pswqtotal))}). There were
no outliers (> 3SD) on these measures. The mean age of participants was
31.38 years (${SD}$ = 9.99 years).

\begin{figure}[!h]
  \centering
  \includegraphics[width=140mm]{/home/paul/Documents/psychology/msc/M210/apprenticeship/dissertation/figure/recruitment.png}
  \caption{Recruitment flowchart}
  \label{flowchart}
\end{figure}

\subsection{Measures and Materials}

All self-report measures were created using Lime Survey
\parencite{limesurvey} and completed using a web browser (see
\cref{app:surveys}). Ecological validity was good, with all except the
pre self-report measurements taken outside of a laboratory environment.

\subsubsection{Pre--Post self-report measures}

The following measures were taken before the first and after the last
dot-probe/ABM sessions.

\paragraph{RRS}

The Ruminative Responses Scale (RRS) is a 22 item measure of
trait rumination, with item scores ranging from 1--4. The RRS is
valid and reliable, having an expected Cronbach's $\alpha$ of .85
\parencite{treynor_rumination_2003}. Questions on the RRS were asked
in relation to the previous 4 weeks, to correspond approximately with
the month before the study (pre) and time within the study (post)
(see \cref{app:surveys}).

\paragraph{GAD-7}

The GAD-7 is a 7 item measure of Generalised Anxiety Disorder (GAD),
with items relating to the previous 2 weeks, and scores ranging from
0--3. The GAD-7 is an efficient, internally reliable (Cronbach's $\alpha$
> .85) tool for assessing GAD severity in clinical research, with good
test-retest reliability \parencite{spitzerrl_brief_2006}.

\paragraph{PHQ-9}

The 9 item Patient Health Questionnaire Depression (PHQ-9) is a brief,
reliable (Cronbach's $\alpha$ > .85) and valid measure of depression
severity \parencite{kroenke_phq9_2001}. Item scores range from 0--3,
and questions relate to the previous 2 weeks.

\paragraph{PSWQ}

The 16 item Penn State Worry Questionnaire (PSWQ) is an internally
consistent measure of trait worry with good test-retest reliability
\parencite{meyer_development_1990}.  Item scores range from 1--5.

\subsubsection{Case-series self-report measures}

The following measures were taken approximately every 24 hours, except
where sessions were postponed.

\paragraph{GRS}

The Goal Rumination Scale (GRS) is a 7 item measure of state rumination
towards a specific problem \parencite{schultheiss_role_2008}.  Item scores
range from 1--7, with items 5--7 reversed. Reliability of the GRS is
good (Cronbach's $\alpha$ = .87), based on a single sample of $N$ =
101. Questions on the GRS were asked in relation to the last 24 hours.

\paragraph{PANAS-SF}

The 10 item, short form Positive and Negative Affect Schedule
\parencite[PANAS-SF,][]{mackinnon_short_1999} measures positive affect
(PA, Cronbach's $\alpha$=.78) and negative affect (NA, Cronbach's
$\alpha$=.87). Item scores range from 1--5. Although the PANAS PA
scale hows significant negative correlations with depression measures
\parencite{watson_development_1988}, the PANAS-SF PA items (`determined',
`alert', `inspired', `enthusiastic', `excited') are underrepresented at
the negative pole of positive affect. Therefore, to improve detection
of our hypothesised change in depression, we added items `sad' and
`depressed' to the PANAS-SF, our rationale being that they would
correlate negatively with PA and positively with NA. To directly assess
our hypothesised changes in anxiety we also added items `anxious' and
`worried', which we expected to correlate positively with NA. Questions
on the PANAS-SF were asked in relation to the last 24 hours.

\subsubsection{Dot-probe task}

Our version of the dot-probe task used word-pair stimuli (see figure
\ref{fig:dotprobe}) and was based on \textcite{yang_attention_2015}. We
used two sets of visual word stimuli in the dot-probe task. A
set of Negative-Neutral (N-word) pairs based on affective norms
\parencite{citron_how_2014}, and a set of Ideographic-Neutral (I-word)
pairs associated with a current concern chosen by each participant.

\begin{figure}[!ht]
  \centering
  \includegraphics[width=200mm,height=150mm]{/home/paul/Documents/psychology/msc/M210/apprenticeship/dissertation/dot_probe_kb.pdf}
  \caption{Example dot-probe trial for a right-handed participant,
  in which the negative word (\textsf{USELESS}) appears at the upper
  location, and the neutral word (\textsf{WHISPER}) appears at the
  lower location.  Correct responses are shown for a subsequent probe
  appearing at either the upper or lower location.}
  \label{fig:dotprobe}
\end{figure}

Each trial began with an 25 x 25 pixel (7 pixel thick) white fixation
cross centred on a black screen. After 500ms, this was replaced by a word
pair from the current stimulus set.  One word from the pair appeared
above the fixation cross location and one below. Word pairs were 125
pixels high with a vertical space between the upper and lower words such
that the stimuli subtended a visual angle of approximately 2$^{\circ}$
\footnote{This angle was calculated using a height measurement of the
visible area of each participant's computer display, and the assumption
that participants followed the instruction to sit approximately 60cm
from the screen.}. Neutral words occurred with equal frequency at the
upper or lower positions. After 1250 ms, the word pair was replaced by
either a greater than (\texttt{>}) symbol or less than (\texttt{<})
symbol at a random letter location within one of the previous word
locations. As our aim was to guarantee attentional engagement with word
stimuli, this exposure duration was chosen as being slightly higher than
the 1000 ms in which vigilance for negative words has been shown to be
positively correlated with measures of depressed mood and vulnerability
\parencite{bradley_attentional_1997}. Furthermore, attentional biases
are more frequently observed when self-relevant negative information is
presented for longer durations \parencite{koster_understanding_2011},
and attentional biases in depression are critically dependent on longer
(1000 ms) exposure durations \parencite{donaldson_rumination_2007}.

 Probes appeared with equal
frequency at upper and lower locations. The only valid keyboard responses
were greater than (\texttt{>}) and less than (\texttt{<}). The probe
remained on the screen until the participant pressed a valid key. A
correct response was recorded if the key-press matched the probe
symbol. There was no feedback for incorrect responses. A blank screen
with a random inter-trial interval (ITI) between 100-500ms followed
each trial. Participants were instructed to respond as quickly and
accurately as possible.  Each dot-probe block consisted of 96 trials
and took approximately 5 minutes to complete.

The task was developed using OpenSesame, an open-source experiment builder
for the social sciences \parencite{mathot_opensesame_2011}. OpenSesame
was chosen as a package which was relatively easy to install on Windows,
Macintosh (OSX ${\geq}$ 10.9) and Linux operating systems, thereby
eliminating any dependencies on a web server for software development or
data collection. Installation instructions for were created using screen
capture software and uploaded to YouTube.

After removing inaccurate trials or those with response times (RTs)
exceeding 3 standard deviations beyond the mean, attentional bias scores
were calculated from the remaining RTs using the equation \begin{equation}
  Attentional\ bias\ score = [(NuPl + NlPu) - (NuPu + NlPl)]/2\label{eq:1}
\end{equation} where ${N}$ = Negative word, ${P}$ = Probe, ${u}$ =
upper, ${t}$ = lower \parencite{bradley_attentional_1997}.  A bias
towards negative words is reflected in longer latencies for probes
at the opposite location (left-hand side of equation \eqref{eq:1})
and shorter latencies for probes at the same location (right-hand side
of equation \eqref{eq:1}). Therefore, more positive scores reflect an
attentional bias towards (i.e. vigilance for) negative words relative
to neutral words, whereas more negative scores indicate avoidance
\parencite{bradley_attentional_1997}.

\subsubsection{ABM task}

The ABM task used three minor adjustments to the dot-probe paradigm
dot-probe to ${modify}$, rather than measure attentional bias. First,
there were double the number (192) trials in each block. Second, only
N-word pairs were used as stimuli. Finally, probes in ABM trials always
appeared at the neutral word location. Thus, responses required repeated
orientation of attention away from the negative word in the pair. Each
ABM block took approximately 15 minutes.

\subsubsection{N-word pairs}

The Sussex Affective Word List (SAWL) \parencite{citron_how_2014} was
used to create 66 N-word stimulus pairs. Starting with 66 words rated
most negative and most neutral, pairs were created by matching words
of equivalent character length, drawing additional words from the SAWL
as necessary to ensure that all pairs were matched on length. A small
number of pairs which appeared to be semantically related were adjusted
by replacing the neutral word in the pair with an alternative from
the SAWL.  Independent samples t-tests showed significant differences
(${P}$s {\textless} .001) for mean ratings of valence and arousal (see
\cref{app:nwordttests}). Pairs were matched for frequency, imageability,
familiarity, number of characters and number of syllables (all ${P}$s
{\textgreater} .16) (see \cref{app:nwordttests}). In addition, the mean
valence between members of any pair was at least 1.44 (Mean: 2.15, ${SD}$
= 0.37). To form the stimulus blocks, pairs were ranked by descending
mean valence difference.  The 6 pairs with the lowest difference were
assigned to the ``spare'' block, used where I-words were present in the
N-word set (see below). The remaining 60 pairs were divided at every
10 word boundary, forming 6 groups. Each experimental block of 6 words
was created by taking the top pair from each group, until all groups
were exhausted, thereby creating 10 blocks with a mixture of valence
differences. The complete N-word list can be seen in \cref{app:nwordlist}

\subsubsection{I-word pairs}
\label{sec:iwordpairs}

We refer to ideographic words (I-words) as the set of 6 words chosen
by each participant for their likelihood to induce rumination
about the participant's chosen current concern. Due to the
unpredictability of these words, and the limited number of words in
the SAWL \parencite{citron_how_2014}, a larger data set was required
to matched pairs to I-words. A database of neutrally valenced words was
created including frequency, imageability, familiarity, word length and
number of syllables attributes from the MRC psycholinguistic database
\parencite{wilson_mrc_1988}. A separate table was added to the database
containing 1030 word valence means from the Affective Norms for English
Words (ANEW) dataset \parencite{bradley_affective_1999}.

Two different matching approaches were used, depending on whether
each I-word word was present in, or absent from, the MRC database.
If present, a neutral pair was selected from a pool of words having
a frequency {\textpm}15\% that of the I-word, an ANEW valence mean
(range 1-9) between 4.00 and 6.00 and an equal number of characters.
After selecting a pool of matched words on the preceding criteria,
a best match was found by inspection of candidate words based on
number of syllables, imageability and familiarity.  Some I-words,
such as long words or high frequency words, could not be matched
using these criteria due to lack of available data. In these cases,
a word with the most neutral valence was chosen that also minimised
differences in length and frequency between the word pair. I-words
absent from the MRC database (including proper nouns) were paired with
words selected from a pool of 56 words having a frequency of 1 (on the
assumption that words missing from the database would most likely be
of low frequency), and for which an ANEW valence rating was available.
A word was selected from this pool having an ANEW valence mean between
4.00 and 6.00 and an equal number of characters to the I-word. If an
I-word or its pair was a member of the N-word set, that N-word pair was
substituted with the next available pair from the spare N-words block
with the largest difference in valence. Resulting I-word pairs were
validated by the experimenter's supervisor. The final sets of I-word
pairs for each participant (\cref{tab:iwords}) and their characteristics
(\cref{tab:iwordcharacteristics}) are show in in \cref{app:iwordlist}.

\subsection{Procedure}

People who met the screening criteria and accepted the invitation to
participate, met the researcher at the University of Exeter to complete
the initial 1 hour preparatory session. Participants gave informed,
written consent, in line with the guidelines set by the University
of Exeter School of Psychology Ethics Committee.  Following this they
completed baseline measures for RRS, PHQ-9, GAD-7 and PSWQ using a web
browser and Lime Survey \parencite{limesurvey}.

Using a procedure based on \textcite{roberts_cueing_2013}, the
participant was instructed to select an unresolved current concern (see
\cref{sec:iwordinstructions}), and rated their concern on a 5 item scale,
with each item in the range 1--9 (see \cref{app:concernrating}). The concern
was accepted if ratings for the questions \enquote{How much you have
been thinking about it over the last week?} and \enquote{How much does
it bother you now?} were > 5, and the concern was unlikely to resolve
within the following 5 weeks. All participants' initial concern met
these criteria. Participants wrote a short statement summarising their
concern and recorded the length of time that it had been bothering them.

The participant then generated their ideographic words (I-words). They
were instructed to generate up to 10 English words, excluding
phrases, associated with their concern. When choosing these words,
they were asked to consider \enquote{causes, meanings and implications}
\parencite[][p.55]{watkins_concreteness_2009} relating to their concern,
thereby encouraging abstract construal, which has been associated with
rumination \parencite{watkins_concreteness_2009}. From their list,
they then chose the 6 words most likely to cause them to ruminate about
their concern.

To familiarise themselves with the dot-probe task, participants
then completed a practice block consisting of N-word block 7 and
a set of I-word pairs generated by the experimenter. Whilst this
was underway, the experimenter validated the participant's I-words,
noting any which known to be difficult to match with a pair from the
neutral word database. These including plurals, acronyms, hyphenated
words, words with stems related to an N-word or words longer than
10 characters. After completing the practice block, participants were
instructed to replace any invalid words with synonyms or with alternatives
from their list, where these were available. Care was taken to ensure that
the semantics of any adjusted words were chosen by the participant without
influence from the experimenter (see \cref{sec:iwordinstructions}). All
participants successfully generated 6 I-words. They rated the valence
of each word in relation to their concern on a 7-point scale, using
instructions based on \textcite{citron_how_2014}. Participants then
completed a distraction task to attenuate the effects of rumination
\parencite{nolen-hoeksema_rethinking_2008} for 5 minutes (see
\cref{app:distraction}).

Participants were given an information sheet to help them install
and complete the computer task (see \cref{app:taskinstructions}). As a
motivational aid, they were also given a printed calendar on which to plan
their daily sessions and cross them off when completed. Implementation
intentions have been shown to improve the goal-directed behaviour
\parencite{gollwitzer_implementation_1999}, so participants were
instructed to write on the calendar sheet a statement indicating an
approximate time when they would complete each session. If requested,
the experimenter installed OpenSesame \parencite{mathot_opensesame_2011}
on the participant's laptop. The initial session ended with the
experimenter and participant agreeing a time on the same or the
following day when the experimenter could be available to support the
participant whilst installing the computer task on their own computer
and completing their first session. All participants successfully
completed the preparatory session (see \cref{app:initialsession} for
full details of the session protocol). The experimenter then prepared
the files required for the participant to run the computer task. These
consisted of the dot-probe/ABM program, I-word pairs, N-word pairs, the
participant's randomisation schedule\footnote{Randomisation schedules
were generated using the \texttt{SCRT} \parencite{bulte_r_2008}
function \texttt{selectdesign(design=AB,MT=35,limit=8)}.}, a stimulus
configuration file and a configuration file to position stimuli based
on the participant's screen height. These files were emailed to the
participant for installation.

\subsubsection{Case-series}

Participants were instructed to complete all experimental sessions on a
computer at their home. Each day, the experimenter sent participants a
templated email containing instructions on how to complete the session
(see \cref{app:reminder}). For the first session, additional instructions
included a link to the installation video on YouTube. Participants
began each session by completing the dot-probe task (phase A) or the ABM
training, followed by the dot-probe (phase B). Using a web browser, they
then used Lime Survey to upload their task data, record whether their
concern was still unresolved and complete PANAS-SF and GRS measures. On
a daily basis, the experimenter recorded whether each participant
had completed a session and, if so, their accuracy on the task. The
experimenter periodically sent additional emails to motivate participants
by notifying them of their progress, to ensure their well-being if 3
consecutive sessions were skipped, and to prepare them for the slightly
longer task when transitioning to phase B. From session 25 onward,
sessions ended with a message informing the participant of the amount
they had earned so far. Participants provided post-intervention RRS,
PHQ-9, GAD-7 and PSWQ measures using the Lime Survey website within
approximately 12 hours of completing the final session. On exiting the study, all
participants were emailed debrief information \cref{app:debrief} and
information about sources of support \cref{app:support} and were paid
for their participation.

\subsubsection{Stimulus allocation}

In phase A, dot-probe blocks consisted of 12 word pairs; the 6 I-word
pairs and 6 N-word pairs. Session 1 used pairs 1--6 from the 66 N-word
set, session 2 used pairs 7--12, and so on. Thus, bias associated with
the participant's ideographic words was measured at every session,
whereas the more general negative valence associated with N-words was
distributed across measurement times. In phase B, dot-probe measurement was
preceded by ABM blocks containing only N-words. To detect ${generalised}$
changes in attentional bias in relation to emotional valence, rather
than changes in bias to specific stimuli \parencite{see_reduction_2009},
phase B dot-probe blocks only contained N-words not previously exposed in
any preceding ABM block. To guarantee enough stimuli when randomisation
resulted in a long phase B, the same 6 N-words were used for 3 consecutive
ABM training sessions. N-words from previous ABM blocks were included in
subsequent ABM blocks. For example, the first 3 ABM blocks used N-words
1--6 and the subsequent dot-probe used N-words 7--12. The fourth ABM
block used N-words 1--12 and the subsequent dot-probe used N-words 13--18,
and so on. A random draw was used to select the 192 stimuli for each ABM
session. As with phase A, the 6 I-words were present in every dot-probe
block. An example stimulus allocation for a randomisation schedule is
shown in \cref{tab:stim}.

\input{procedure/stim.tex}

% handle weird gaps that appeared between paragraphs near this page
\raggedbottom
\section{Ethical Considerations}

Because screening measures were submitted remotely, depression was
measured using the PHQ-8 which omits one item measuring suicidal ideation.
Anyone scoring ${\geq}$ 10 on the PHQ-8 \parencite{kroenke_phq8_2009}
received practical, supportive information about resources available
to people who may be suffering from depression. The researcher
completed training in implementing the latest risk protocol employed
by the University of Exeter, Mood Disorders Centre. Risk cover by a
clinically trained member of staff was arranged in advance of each PHQ-9
(which includes a suicidal ideation question) that was administered to
participants. No participants triggered the risk protocol.

A potential risk of harm was identified arising from increasing
rumination in high trait ruminators, along with the burden of a long
testing period. The experimenter mitigated this risk by keeping in
regular contact with participants, notably when more than two testing
sessions were skipped. Any concerns were raised with the researcher's
supervisor. On leaving the study, all participants were emailed a copy
of the support information for people who may suffer from depression.

Participants were not identifiable from their electronic data. Online
measures were stored on a secure digital filing system and all other
data on a memory stick. Any sensitive written information was stored
in a locked filing cabinet. A detailed ethical submission was approved
by the University of Exeter, School of Psychology Ethics Committee
(see \cref{app:ethics}).

\section{Analyses}
\label{analyses}

Data were analysed using using R version 3.1.0
\parencite{rcoreteam_r_2014} and additional packages
\texttt{corrplot} \parencite{wei_corrplot_2013},
\texttt{lsr} \parencite{navarro_learning_2015},
\texttt{pwr} \parencite{champely_pwr_2015}, \texttt{psy}
\parencite{falissard_psy_2012}, \texttt{SCMA} \parencite{bulte_scma_2015},
\texttt{SCRT} \parencite{bulte_scrt_2015} and \texttt{SCVA}
\parencite{bulte_scva_2015}.

<<power, echo=FALSE, error=TRUE>>=
library(pwr)
library(stringr)
format_power <- function(x) {
  x <- sprintf("%0.2f",x)
  str_replace(as.character(x), "^0\\.", ".")
}

# RRS d=.49 (Yang et al., 2015)
rrs_pwr <- pwr.t.test(d=.49,n=12,sig.level=0.05,type="paired",alternative="two.sided")
rrs_pwr <- format_power(rrs_pwr$power)

# BDI-II d=1.50 (Yang et al., 2015)
bdi_pwr <- pwr.t.test(d=1.5,n=12,sig.level=0.05,type="paired",alternative="two.sided")
bdi_pwr <- format_power(bdi_pwr$power)

# STAI-T d=.88 (Yang et al., 2015)
stai_pwr <- pwr.t.test(d=.88,n=12,sig.level=0.05,type="paired",alternative="two.sided")
stai_pwr <- format_power(stai_pwr$power)

# PSWQ d=.51 (Enock & Hofmann, 2014)
pswq_pwr <- pwr.t.test(d=.51,n=12,sig.level=0.05,type="paired",alternative="two.sided")
pswq_pwr <- format_power(pswq_pwr$power)
@

\subsection{Pre--Post comparisons}

Two-tailed, paired samples t-tests were used to compare participants'
pre and post ABM training measures of rumination (RRS), depression
(PHQ-9), anxiety (GAD-7) and worry (PSWQ). Although these tests
were likely to be underpowered, using a similar ABM procedure,
\textcite{yang_attention_2015} found significant post training reductions
in rumination, using RRS (${d}$=.49), depression, using BDI-II
\parencite{beck_manual_1996} (${d}$=1.50) and anxiety, using STAI-T
\parencite{spielberger_manual_1983} (${d}$=.88). Given these effect sizes,
12 participants and $\alpha$ set at .05, two-tailed calculations of power
(1-$\beta$) gave \Sexpr{rrs_pwr} for RRS, \Sexpr{bdi_pwr} for BDI-II and
\Sexpr{stai_pwr} for STAI-T. In practice, these are likely to be lower
as participants in \textcite{yang_attention_2015} were undergraduates
with mild to severe depression in contrast with the current study where
participants with mild depression or above were excluded. Estimates could
also vary due to the different instruments used to measure depression
(PHQ-9) and anxiety (GAD-7) in the current study. In an ABM training
study using smartphones, \textcite{enock_attention_2014} found a
significant post ABM training reduction in PSWQ (${d}$=.51) using a
dot-probe task with neutral and disgust face stimuli. A two-tailed
calculation with 12 participants and $\alpha$ set at .05, gave power
(1-$\beta$) of \Sexpr{pswq_pwr}. In summary, the current study is likely
to be sufficiently powered to detect changes in depression (PHQ-9) and
possibly anxiety (GAD-7), but underpowered to detect changes in rumination
(RRS) and worry (PSWQ).

\subsection{Case-series}

Given the lack of power for some pre-post comparisons, the primary
analyses were visual inspection of graphs and randomisation tests
comparing A and B phases in each case-series for measures of attentional
bias (I-words and N-words), state rumination (GRS) and mood (PANAS-SF).
Visual analyses were carried out using time-series graphs generated
by the R package \texttt{SCVA}\footnote{Minor modifications were
made to the \texttt{SCVA} package to standardise y-axis ranges and to
plot central tendency, trend and variance lines on the same graph.}
\parencite{bulte_when_2012}. Inferential statistics were calculated for
each participant using randomisation tests provided by the R package
\texttt{SCRT} \parencite{bulte_r_2008}.

Randomisation is a nonparametric approach which allows inferential
statistics to be calculated using data from a single-case series
\parencite{bulte_r_2008}. In an AB design, the phase sequence (baseline
followed by intervention) is fixed, therefore it is the point at
which phase A transitions to phase B which is randomised. Under
the null hypothesis, a test statistic for a particular set of
observations would not differ regardless of where the transition
from A to B occurs. Randomisation tests hold the observation scores
constant and calculate the test statistic for all possible transition
permutations. Once sorted, the ${p}$ value is the proportion of
test statistics greater than or equal to the observed test statistic
\parencite{onghena_customization_2005}. A one-tailed randomisation test
(test statistic = \texttt{A-B}) was performed for N-word attentional bias
scores as these were predicted to be more negative after ABM training. All
other randomisation tests were two-tailed (test statistic = \(\lvert
\texttt{A-B}\rvert\)).  In addition to the single-case randomisation
tests, a meta-analysis \parencite[][p.64]{onghena_customization_2005}
was carried out across all participants for each outcome measure using
the R package \texttt{SCMA} \parencite{bulte_singlecase_2013}. This
allowed for significance testing across participants above the
${p}$=.05 level, even though the randomisation tests could not detect
significance at this level for participants who completed less than
35 sessions. The meta-analysis used an additive approach, which has
a greater probability of yielding significant results when there are
treatment effects \parencite{edgington_additive_1972}. The percentage
of nonoverlapping data (PND) is an effect size measure frequently
used in single-subject research, and is the percentage of treatment
phase observations that do not overlap data in the baseline phase
\parencite{scruggs_pnd_2013}. \textcite{scruggs_early_1986} consider
treatments with PND scores ${\geq}$ 90\% as highly effective, scores of 70\%--90\%
as fair, scores of 50\%--70\% as questionable effects, and scores <~ 50\%
as unreliable.  PND was calculated using the R package \texttt{SCMA},
using \texttt{PND-} for N-words, I-words, NA and depression as the
treatment should case these measures to drop, and \texttt{PND+} for PA
as the treatment should result in an increase in positive affect.

Of the four items added to the PANAS-SF, `sad' and `depressed' correlated
strongly with each other and weakly with PA items on the scale, whereas
`anxious' and `worried' were moderately associated with NA, but not
as highly as the NA scale itself (see \cref{app:mood}). Given these
findings and that PANAS is an established measure, we analysed three
mood variables: positive affect (PA scale), negative affect (NA scale)
and `depression' (`sad' and `depressed' items). All questions on the
daily online outcome measures were mandatory, so there was no missing
data for any completed survey.

\section{Results}

Three participants withdrew from the study; one before completing
any sessions due to concerns that the study would worsen their social
anxiety, another who found the time commitment too great after 5 sessions,
and the third after 24 sessions when a holiday meant that they would
be unable to complete sufficient phase B sessions. Dropout was not
predictable for these participants as their screening scores were not
atypical and there were participants scoring higher on both RRS and PSWQ
who nevertheless completed the study. For the remaining participants,
dot-probe/ABM accuracy was above our a priori inclusion threshold of
75\% (see \cref{tab:completed}) and the current concern chosen by each
participant at the preparatory session remained unresolved throughout the
study. Session 32 for participant 7 was omitted from the analyses as the
dot-probe data file for this session was truncated. Session 8 GRS and
PANAS-SF scores for participant 16 were brought forward from session 7,
as the participant completed the dot-probe but not the measures during
session 8, but advised within 12 hours that the scores would have
been identical. To remain in the study, participant 5 switched from a
Windows to Macintosh computer from session 21 onward, and participant
19 completed later sessions in a different country from the one in which
they began the study.

\belowrulesep=1pt
%\aboverulesep=1pt
\input{results/completed.tex}

\subsection{Pre--Post Measures}

Comparisons between outcome measures pre and post ABM training
are summarised in \cref{tab:prepost}. There were no outliers
(> 3SD) on GAD-7, PHQ-9, PSWQ or RRS scores before or after ABM
training. Cronbach's $\alpha$ was acceptable for GAD-7 and PSWQ, good
for PHQ-9 and and excellent for RRS. There were no significant pre-post
ABM training differences (all ${P}$s {\textgreater} .05) on any of these
outcomes. There was a small increase in trait anxiety (GAD-7, ${d}$ =
.22) and a very small reduction in trait rumination (RRS, ${d}$ = .17).

<<external, cache=FALSE, echo=FALSE>>=
knitr::read_chunk('../opensesame/dotprobe/prepost.R')
knitr::read_chunk('../opensesame/dotprobe/nwords.R')
knitr::read_chunk('../opensesame/dotprobe/iwords.R')
@

\setlength\tabcolsep{1mm}
<<prepost, results='asis', echo=FALSE, error=TRUE>>=
@

\subsection{Visual Analyses}
\label{sec:va}

The principal features of interest when visually analysing AB
case-series data are central tendency and its within-phase trends,
within-phase variability, and changes in level (adjacent data
points of separate phases) \parencite{morley_graphical_1991}. In the
following graphs, the broadened median (BMED) is used as a measure of
central tendency as it is both sensitive to a reasonable proportion
of the data, and resistant to outliers in relatively small samples
\parencite{morley_graphical_1991}. Two types of trend line are plotted
to reduce bias (often due to outliers) when visually interpreting raw
data points. A robust linear trend in central tendency is shown using
the split middle method \parencite{morley_graphical_1991}\footnote{This
method results in two lines where there are an odd number of points
in a phase. Poor alignment between these lines indicates a poor fit
\parencite{morley_graphical_1991}.}. Trends in variability are plotted
using the trimmed (10--20\% of outliers from each phase), trended range
which reduces the influence of outliers, and of trends in central tendency
\parencite{morley_graphical_1991}.

\subsubsection{N-word attentional bias}

see \cref{sec:introduction}

Visual inspection indicated a post-ABM reduction in attentional
bias towards N-words as hypothesised in some, but not all
participants. Changes in attentional bias for N-word pairs are summarised
in \crefrange{fig:va-n-a}{fig:va-n-b}. As mentioned previously, more
positive bias scores reflect vigilance for negative words, whereas more
negative scores indicate avoidance. All participants had an initial BMED
score close to 0, indicating a lack of any large attentional bias in
either direction. In phase B, 7 participants (5, 6, 8, 10, 11, 16 and 19)
showed a more negative bias, although participant 5 had 2 large, negative
scores. In phase A, linear trends in score increased for 7 participants
(5, 6, 8, 11, 15 and notably 12), decreased for 4 participants (9, 16,
18 and 19) and remained flat for 2 participants (7 and 10). Of the trends
in phase B which were a good fit, relative to phase A, participant 11
reversed in the hypothesised direction, 3 (participants 8, 12 and 15)
continued in the same direction, and 2 (participants 9 and 19) reversed
contrary to the hypothesised direction. Phase A variance was small
in participant 18 but similar in all other participants. It was also
stable in most participants but increased in 2 (participants 9 and 15)
and decreased in 3 (participants 11, 18 and 19). Variance increased in
a number of participants on transition to phase B but by the end was
similar to levels in phase A. Two outliers explain the large phase B
change in variance for participant 5.

\begin{figure}[!htbp]
  \begin{subfigure}[!htbp]{\textwidth}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/5/p5_n.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/6/p6_n.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/7/p7_n.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/8/p8_n.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/9/p9_n.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/10/p10_n.jpg}
    \caption{N-word attentional bias scores for participants 5--10.}
    \label{fig:va-n-a}
    \end{subfigure}
\end{figure}

\begin{figure}
\ContinuedFloat
  \begin{subfigure}[!htbp]{\textwidth}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/11/p11_n.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/12/p12_n.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/15/p15_n.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/16/p16_n.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/18/p18_n.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/19/p19_n.jpg}
    \caption{N-word attentional bias scores for participants 11, 12, 15, 16, 18 and 19.}
    \label{fig:va-n-b}
  \end{subfigure}
\caption{Dashed line = phase transition. \protect\strokeA{} broadened
median, \protect\strokeB{} split middle linear trend, \protect\strokeC{}
trimmed trended range (see \cref{analyses}).}
\label{fig:va-n}
\end{figure}
\clearpage

\subsubsection{I-word attentional bias}

Visual inspection indicated a reduction in attentional bias in the
majority of participants. Changes in attentional bias for I-word pairs
are summarised in \crefrange{fig:va-i-a}{fig:va-i-b}. As with N-words,
more positive bias scores reflect vigilance for negative words, more
negative scores indicate avoidance, and there were no large initial
attentional biases in either direction. In phase B, 10 participants showed
a more negative attentional bias, and 2 (participants 11 and 12) a more
positive bias. Of the linear trends in phase A which were a good fit, 6
(participants 7, 8, 10, 18 and 19) increased and 5 (participants 5, 6,
9, 12 and 16) decreased. Of the trends in phase B which were a good fit,
relative to phase A, 2 (participants 18 and 19) became more negative and 2
(participants 8 and 9) continued in the same direction. Phase A variance
was small in participant 18 but similar in all other participants. It
was also stable in most participants but increased in 2 (8 and 10) and
decreased in 3 (7, 15 and notably 18).  Relative to the end of phase A,
variance in phase B increased in 6 participants (5, 6, 9, 12, 15 and 18),
and decreased in 2 (participants 7 and 19).

\begin{figure}[!htbp]
  \begin{subfigure}[!htbp]{\textwidth}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/5/p5_i.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/6/p6_i.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/7/p7_i.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/8/p8_i.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/9/p9_i.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/10/p10_i.jpg}
    \caption{I-word attentional bias scores for participants 5--10.}
    \label{fig:va-i-a}
  \end{subfigure}
\end{figure}

\begin{figure}
\ContinuedFloat
  \begin{subfigure}[!htbp]{\textwidth}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/11/p11_i.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/12/p12_i.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/15/p15_i.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/16/p16_i.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/18/p18_i.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/19/p19_i.jpg}
    \caption{I-word attentional bias scores for participants 11, 12, 15, 16, 18 and 19.}
    \label{fig:va-i-b}
  \end{subfigure}
\caption{Dashed line = phase transition. \protect\strokeA{} broadened
median, \protect\strokeB{} split middle linear trend, \protect\strokeC{}
trimmed trended range (see \cref{analyses}).}
\label{fig:va-i}
\end{figure}
\clearpage

\subsubsection{State rumination (GRS)}

Changes in GRS scores are summarised in
\crefrange{fig:va-grs-a}{fig:va-grs-b}. Relative to phase A, BMED GRS
scores reduced in 9 participants (5, 6, 8, 9, 10, 11, 15, 18 and 19)
indicating a reduction in rumination towards their chosen concern. These
reductions were largest in participants 10, 5 and 11, although initial
GRS high in participant 11. Phase A GRS showed a downward trend for
10 participants, being especially steep in participants 5, 10, 18 and
19. Participant 12 showed a steep linear increase in phase A. The
majority of linear trends in phase B were a poor fit. The phase A
downwards trends reduced in phase B for participants 8, 11, 18 and
19, becoming slightly positive for participant 15. Phase A variance
was generally large and reduced in most participants (notably 5, 6,
9 and 18), with moderate and large increases in participants 16 and 12
respectively. Relative to phase A, phase B variance was mostly reduced,
exceptions being participants 11, 16 and 19. Variance in phase B was
stable or reducing in most participants (notably 7, 8, 12 and 18) with
moderate and large increases in participants 19 and 16 respectively.

\begin{figure}[!htbp]
  \begin{subfigure}[!htbp]{\textwidth}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/5/p5_grs.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/6/p6_grs.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/7/p7_grs.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/8/p8_grs.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/9/p9_grs.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/10/p10_grs.jpg}
    \caption{GRS scores (range 1--49) for participants 5--10.}
    \label{fig:va-grs-a}
  \end{subfigure}
\end{figure}

\begin{figure}
\ContinuedFloat
  \begin{subfigure}[!htbp]{\textwidth}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/11/p11_grs.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/12/p12_grs.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/15/p15_grs.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/16/p16_grs.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/18/p18_grs.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/19/p19_grs.jpg}
    \caption{GRS scores (range 1--49) for participants 11, 12, 15, 16, 18 and 19.}
    \label{fig:va-grs-b}
  \end{subfigure}
\caption{Dashed line = phase transition. \protect\strokeA{} broadened
median, \protect\strokeB{} split middle linear trend, \protect\strokeC{}
trimmed trended range (see \cref{analyses}).}
\label{fig:grs}
\end{figure}
\clearpage

\subsubsection{Positive Affect (PA)}

Visual inspection indicated increased PA for most participants. Changes in
PA scores are summarised in \crefrange{fig:va-pa-a}{fig:va-pa-b}. Relative
to phase A, BMED phase B PA scores increased in 7 participants (5, 9,
10, 11, 15, 18 and notably 6), decreased slightly in 3 participants (8,
12 and 19), decreased more markedly in participant 16 and remained stable
in participant 7. Where there was a linear fit, phase A PA showed an
upward trend for 6 participants, being especially steep for participant
9, a downward trend for 2 participants, and was relatively stable for
2 participants. Where there was a linear fit in both phases, trends
continued in the same direction for participants 11 and 15, and became
more negative for participant 19. PA variance between phases A and B
increased in participants 6, 10, 15, 18 and notably 11, and decreased
notably in participant 19.

\begin{figure}[!htbp]
  \begin{subfigure}[!htbp]{\textwidth}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/5/p5_pa.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/6/p6_pa.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/7/p7_pa.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/8/p8_pa.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/9/p9_pa.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/10/p10_pa.jpg}
    \caption{PA scores (range 1--25) for participants 5--10.}
    \label{fig:va-pa-a}
  \end{subfigure}
\end{figure}

\begin{figure}
\ContinuedFloat
  \begin{subfigure}[!htbp]{\textwidth}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/11/p11_pa.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/12/p12_pa.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/15/p15_pa.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/16/p16_pa.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/18/p18_pa.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/19/p19_pa.jpg}
    \caption{PA scores (range 1--25) for participants 11, 12, 15, 16, 18 and 19.}
    \label{fig:va-pa-b}
  \end{subfigure}
\caption{Dashed line = phase transition. \protect\strokeA{} broadened
median, \protect\strokeB{} split middle linear trend, \protect\strokeC{}
trimmed trended range (see \cref{analyses}).}
\label{fig:pa}
\end{figure}

\clearpage
\subsubsection{Negative Affect (NA)}

Visual inspection indicated decreased NA for most participants. Changes in
NA scores are summarised in \crefrange{fig:va-na-a}{fig:va-na-b}. Relative
to phase A, BMED phase B NA scores decreased in 8 participants (5, 6, 9,
10, 11, 12, 15, 16 and 18), and increased in 3 participants (7, 8 and
19). Where there was a linear fit, phase A NA showed an downward trend
for 6 participants being especially steep for participant 18, an upward
trend for 1 participant and was relatively flat for 2 participants.
Where there was a linear fit in both phases, trends continued downwards
for participants 6, 11 and 12, and reversed sharply from positive
to negative for participant 8.  NA variance between phases A and B
decreased in participants 5, 10 and notably 8 and increased notably in
participant 11.

\begin{figure}[!htbp]
  \begin{subfigure}[!htbp]{\textwidth}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/5/p5_na.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/6/p6_na.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/7/p7_na.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/8/p8_na.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/9/p9_na.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/10/p10_na.jpg}
    \caption{NA scores (range 1--25) for participants 5--10.}
    \label{fig:va-na-a}
  \end{subfigure}
\end{figure}

\begin{figure}
\ContinuedFloat
  \begin{subfigure}[!htbp]{\textwidth}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/11/p11_na.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/12/p12_na.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/15/p15_na.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/16/p16_na.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/18/p18_na.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/19/p19_na.jpg}
    \caption{NA scores (range 1--25) for participants 11, 12, 15, 16, 18 and 19.}
    \label{fig:va-na-b}
  \end{subfigure}
\caption{Dashed line = phase transition. \protect\strokeA{} broadened
median, \protect\strokeB{} split middle linear trend, \protect\strokeC{}
trimmed trended range (see \cref{analyses}).}
\label{fig:na}
\end{figure}

\clearpage
\subsubsection{Depression}

Visual inspection indicated decreased depression for most
participants. Changes in depression scores are summarised in
\crefrange{fig:va-d-a}{fig:va-d-b}. Initial depression scores were
moderate to low for all participants. Relative to phase A, BMED phase
B depression scores decreased in 7 participants (6, 8, 9, 11, 12, 15
and 18 ), increased in 4 participants (5, 10, 16 and 19) and remained
the same in participant 7. Where there was a linear fit, phase A NA
showed an downward trend for 4 participants being especially steep
for participants 9 and 18, an upward trend for 1 participant and was
relatively flat for 4 participants. Where there was a linear fit in
both phases, trends continued in the same direction for participants 7,
8 and 10, stabilised close to the bottom of the scale for participants
9, 15 and 18, and increased sharply for participant 19.  Variance in
depression between phases A and B decreased in participants 7, 9 and 18
and increased in participants 10 and 16.

\begin{figure}[!htbp]
  \begin{subfigure}[!htbp]{\textwidth}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/5/p5_d.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/6/p6_d.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/7/p7_d.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/8/p8_d.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/9/p9_d.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/10/p10_d.jpg}
    \caption{Depression scores (range 1--10) for participants 5--10.}
    \label{fig:va-d-a}
  \end{subfigure}
\end{figure}

\begin{figure}
\ContinuedFloat
  \begin{subfigure}[!htbp]{\textwidth}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/11/p11_d.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/12/p12_d.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/15/p15_d.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/16/p16_d.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/18/p18_d.jpg}
    \includegraphics[plotwh]{/media/paul/2E95-1293/study/participants/19/p19_d.jpg}
    \caption{Depression scores (range 1--10) for participants 11, 12, 15, 16, 18 and 19.}
    \label{fig:va-d-b}
  \end{subfigure}
\caption{Dashed line = phase transition. \protect\strokeA{} broadened
median, \protect\strokeB{} split middle linear trend, \protect\strokeC{}
trimmed trended range (see \cref{analyses}).}
\label{fig:d}
\end{figure}

\clearpage
\subsection{Inferential Statistics}

N-word and I-word randomisation tests and meta-analysis results are
summarised in \cref{tab:rt}. Although there was a reduction in attentional
bias for I-words for 7 participants (6, 8, 9, 10, 16, 18 and 19), none of
the differences were significant (all ${P}$s < .05). The meta-analysis
across participants was also non-significant (${p}$ = .806). There was
a reduction in attentional bias for N-words in 7 participants (5, 6, 8,
10, 11, 16 and 19), although the difference was only significant (${p}$ =
.05) for participant 11 with an unreliable effect (${PND}$ = 29.15\%). The
meta-analysis across participants was significant (${p}$ = .046).

State rumination (GRS) randomisation tests and meta-analysis results
are summarised in \cref{tab:grs}. Although there was a reduction in
GRS score 9 participants (5, 6, 8, 9, 10, 11, 15, 18 and 19), none of
the differences were significant (all ${P}$s < .05). Increases in GRS
for participants 6, 12 and 16 were also non-significant. The
meta-analysis across participants was also non-significant (${p}$ = .563).

Mood variable (PA, NA and depression) randomisation tests and
meta-analysis are summarised in \cref{tab:panas}. There was an increase
in PA for 9 participants (5, 6, 7, 9, 10, 11, 12, 15 and 18), although the
difference was only significant (${p}$ = .05) for participant 8. Decreases
in PA for participants 8, 16 and 19 were also non-significant, as
was the meta-analysis across all participants for PA (${p}$ = .167).
Although there was decrease in NA for 9 participants (5, 6, 9, 10,
11, 12, 15, 16 and 18), none of the differences were significant (all
${P}$s < .05). Increases in NA for participants 7, 8 and 19 were also
non-significant, as was the meta-analysis across all participants for NA
(${p}$ = .801). Depression scores decreased in 5 participants (6, 9, 11,
15 and 18) and increased in 7 participants (5, 7, 8, 10, 12, 16 and 19),
however all differences were non-significant (${P}$s < .05).

\clearpage

\setlength\tabcolsep{1mm}

\input{results/rt.tex}

\begin{center}
\input{results/grs.tex}
\end{center}

\input{results/panas.tex}

\clearpage
\section{Discussion}

\subsection{Interpretation}

Pre-post. Point out that these are trait measures so relatively coarse. Comment on (lack of) power.

Underpowered to detect changes in rumination (RRS) and worry (PSWQ) and
both of these measures showed moderate but non-significant effects. Might
be significant with more power.

Were most Ps high worry but the dot-probe exposure configured for high rumination (1250ms)?
Would emotional Stroop be better?

"In contrast with current theories, we found that 34\% of participants
expressed AB towards threat stimuli, 20.8\% AB away from threat stimuli,
and 34\% AB towards some categories of threat stimuli and away from
others." \parencite{zvielli_dynamics_2014}. Perhaps this is reflected
in my results for worriers? Were they "threatened" by their concern?

\subsubsection{Limitations}

\begin{itemize}
\item Duh! I could have easly matched the stimulus exposure to the RRS (1250ms)/PSWQ(<ms) score!

\item I could calculate change in the RRS brooding subscale to
specifically measure changes to R*N*T?

\item dot-probe has poor internal consistency and test-retest reliability
in non-clinical samples \textcite{schmukle_unreliability_2005}
(only measuring chance error variance?). N2pc isn't much better than
RT \parencite{kappenman_behavioral_2014}. This ties in with stimulus
durations. In summary, need more tasks which are more accurate and precise
measures of AB. Most of this focusses on anxiety, but the same is needed
for AB in depression.

\item could the uncontrolled environment have amplified this problem?

\item I could calculate the internal consistency (split-half correlations
and Cronbach's alpha) and test-retest reliability of the dot-probe
using \textcite{schmukle_unreliability_2005}. Poor correlations with
STAI could also explain null findings for GAD-7.

\item self-report measures, there are more objective measures?
\item What happens when problem resolves?
\item Only 2 measurement times (pre/post) vs. daily changes in AB, mood, rumination.
\item Not sure about correlations between PANAS-SF and depression
\item Didn't MBD analysis due to differing numbers of sessions.
\item Did I really demonstrate *disengagement*? Felicity said the dot-probe doesn't do this.
\end{itemize}

"the provision of explicit information and instructed practice in
the desired pattern of attentional selectivity, while potentially
enhancing patient acceptability with CBM-A, may eliminate its capacity
to effectively alter anxiety vulnerability." \parencite{grafton_when_2014}

\subsection{Does CBM-A work?}

As mentioned, some say effect sizes are too small to be clinically relevant \parencite{cristea_efficacy_2015}

\enquote{When anxiety and depression were examined separately,
CBM significantly modified anxiety but not depression. There was
a nonsignificant trend toward a larger effect for studies including
multiple training sessions.} \parencite{hallion_metaanalysis_2011}

\enquote{The therapeutic benefit of ABM is rather small for anxiety, while the amount of data
for other symptom categories is limited.} \parencite{mogoase_clinical_2014}
\subsection{moderators}

\enquote{The effects of ABM on attention bias were moderated by stimulus
type (words vs pictures) and sample characteristics (healthy vs. high
symptomatology).} \parencite{beard_efficacy_2012}

\enquote{Moderation analysis of the between-groups effect revealed
a significant effect for ABMT delivered in the clinic (d = 0.34, P =
0.01, CI = 0.07–0.62), and a nonsignificant effect for ABMT delivered
at home} \parencite{linetzky_quantitative_2015}

\subsection{RFW}

Inhibitory control \parencite{koster_understanding_2011}.

"it does not seem very useful to develop new psychotherapies for
depression. There are already many different kinds of psychotherapies,
there is no evidence that one type is considerably more effective than
others, and it is very difficult to show such differences in trials with
sufficient statistical power." \parencite{cuijpers_psychotherapies_2015}

Establish the likely cause(s) before testing potential
cures! Also need to subsequently match the right treatment. Maybe
this explains why treatments are ineffective? More, not less research.

Case-series with randomisation tests is a good, quick way of testing hypothesis

\subsubsection{Causality}

Still unclear and under researched

Martin, Shrira and Startup \parencite{papageorgiou_depressive_2004}
suggest a list of causes even within the goal progress theory model,
all of which would require different treatment approaches.

More specific mechanistic hypotheses e.g. "rumination was related to attentional switching impairments,
specifically in the context of emotional information"
\parencite{koster_rumination_2013}

\subsubsection{Goals}

Were the goals chosen "higher order"? \parencite{martin_ruminative_1996}

\textcite{martin_ruminative_1996} don't claim that goal discrepancies
are the exclusive cause of rumination. So it could be a different cause in
this sample. While they claim the rebound effect of thought suppression
can be explained in terms of goal discrepancies they say it may also
occur in the absence of them, notably in the case of worry.

\textcite{watkins_habitgoal_2014} have sought to unify these theories
by proposing that RNT may be a habit, initiated by goal discrepancies
and subsequently cued by contingent contexts such as mood or physical
location.  They suggest that such automatic, habitual responses come to
depend on context more than the content of particular unresolved goals,
especially when contingent responses involve passive focus on abstractly
construed, negative content.

I only really tested this in one (uncontrolled) context i.e. at home,
and not controlling time of day, mood or degree of state rumination.

An extension of the goal theory and RST (how?!) suggests that rumination
becomes habitual thinking style, cued by context and not related to
any particular goal discrepancy. \textcite{watkins_habitgoal_2014} A
more direct test of the disengagement hypothesis within this framework
makes sense as it's explicitly proposed in the absence of any overt goal
discrepancies .RFW. (looks like it hasn't been tested yet)

\enquote{Thus, people with high implicit motivation were less prone to ruminate
about their goals and people with high goal commitment were more likely
to ruminate. This effect was qualified by a marginally significant
goal commitment x implicit motivation effect, B = 0.319, SE = 0.177,
t(91) = 1.80, p = .07. As shown in Table 5, the interaction was due to a
damping effect of implicit motivation on goal rumination in low-commitment
participants.} \parencite{schultheiss_role_2008}

\subsubsection{rumination}

\begin{itemize}

\item Could individual's current concern(s) indicate the type of bias
modification which might be beneficial? i.e. some psychotherapy to
determine best treatment

\end{itemize}

\subsubsection{CBM}

\begin{itemize}
\item \enquote{CBM had a medium effect on biases (g = 0.49) that was stronger
for interpretation (g = 0.81) than for attention (g = 0.29) biases} \parencite{hallion_metaanalysis_2011}

\item ABM training other than the dot-probe Sigurjonsdottir et. al 2015

\item What is an effective dose?

\item Longevity of effects treatment? Would ABA revert? Problem as people unlikely to keep up training.
\end{itemize}

\subsection{Conclusion}

We know that rumination is associated with depression and anxiety, but
we still don't know enough about it's causes. Greater precision will
produce better treatments.

Premature to ignore cognitive and neuroscientific evidence for potentially
beneficial bottom-up treatments before research has fully tested the
hypotheses that these approaches are generating.

Don't throw the baby out with the bathwater. Internet delivery in itself
could provide opportunities for more precise measurement and personalised
treatments using experience sampling/EMA. Especially with case-series
approach and randomisation tests.

On the one hand this adds to the absence of evidence. On the other hand
it provides methods which add to the body of evidence which distinguish
what how biases can be modified, which biases can be modified and in
which populations these have desired effects on psychopathology.

\printbibliography
%% CAVEAT: \appendices environment breaks \cleveref
\newpage
\appendix
\appendixpage

\setcounter{tocdepth}{2}
\startcontents[sections]
\printcontents[sections]{l}{1}
%\addappheadtotoc
%\todo{appendices: 4000 words max (~250 words/page i.e. 16 pages)}

\section{Survey Measures}
\label{app:surveys}

\begin{sidewaysfigure}[hp]
\includegraphics[width=270mm]{figure/rrs.png}
\caption{Ruminative Responses Scale (RRS) administered using Lime Survey}
\end{sidewaysfigure}

\begin{sidewaysfigure}[hp]
\includegraphics[width=250mm]{figure/gad7.png}
\caption{GAD-7 administered using Lime Survey}
\end{sidewaysfigure}

\begin{sidewaysfigure}[hp]
\includegraphics[width=250mm]{figure/phq9.png}
\caption{PHQ-9 administered using Lime Survey}
\end{sidewaysfigure}

\begin{sidewaysfigure}[hp]
\includegraphics[width=250mm]{figure/pswq.png}
\caption{Penn State Worry Questionnaire (PSWQ) administered using Lime Survey}
\end{sidewaysfigure}

\begin{sidewaysfigure}[hp]
\includegraphics[width=250mm]{figure/panas.png}
\caption{Positive and Negative Affect Schedule (PANAS-SF) administered using Lime Survey}
\end{sidewaysfigure}

\begin{sidewaysfigure}[hp]
\includegraphics[width=250mm]{figure/grs.png}
\caption{Goal Rumination Scale (GRS) administered using Lime Survey}
\end{sidewaysfigure}

\section{N-word stimulus pairs}
\label{app:nwordlist}

\begin{table}[!htbp]
{\tiny
  \begin{tabular}{cllllll}\hline%
    Block & Pair 1 & Pair 2 & Pair 3 & Pair 4 & Pair 5 & Pair 6\\\hline 
    \csvreader[late after line=\\]{../experiment/66_nwords.csv}{Block=\block}%
      {\block & \textsf{\csvcolii}-\textsf{\csvcoliii} & \textsf{\csvcoliv}-\textsf{\csvcolv} &
      \textsf{\csvcolvi}-\textsf{\csvcolvii} & \textsf{\csvcolviii}-\textsf{\csvcolix} &
      \textsf{\csvcolx}-\textsf{\csvcolxi} & \textsf{\csvcolxii}-\textsf{\csvcolxiii}}%
    \hline
  \end{tabular}
}
\end{table}

\section{N-word t-tests}
\label{app:nwordttests}

<<nwords, results='asis', echo=FALSE, error=TRUE>>=
@

\section{Distraction task}
\label{app:distraction}
\input{procedure/distraction.tex}

\section{Task instructions}
\label{app:taskinstructions}
\input{procedure/task_instructions.tex}

\section{I-word stimulus pairs}
\label{app:iwordlist}

<<iwords, results='asis', echo=FALSE, error=TRUE>>=
@

\section{Current Concern Rating Scale}
\label{app:concernrating}

\section{Unresolved goal and I-word generation instructions}
\label{sec:iwordinstructions}
% FIXME: remove supertablular nonsense
%\input{procedure/iwords.tex}

\section{Initial Session Protocol}
\label{app:initialsession}

\section{Example session reminder email}
\label{app:reminder}
\input{procedure/reminder.tex}

\section{Debrief sheet}
\label{app:debrief}
\input{procedure/debrief.tex}

\section{Sources of support information sheet}
\label{app:support}
\input{procedure/support.tex}

\section{Ethical Approval}
\label{app:ethics}

\begin{figure}[hp]
\includegraphics[width=160mm]{figure/ethics_approval.png}
\caption{Notification of ethical approval}
\end{figure}

\section{Correlations for mood measures}
\label{app:mood}

\begin{figure}[h]
\centering
\includegraphics[width=110mm,height=110mm]{figure/PAnas.jpg}
\caption{Correlations between PA scale on PANAS-SF and items `sad' and `depressed'}
\includegraphics[width=110mm,height=110mm]{figure/paNAs.jpg}
\caption{Correlations between NA scale on PANAS-SF and items `anxious' and `worried'}
\end{figure}

\end{document}
