\documentclass[man,floatsintext,a4paper,biblatex]{apa6}
\usepackage[english, british]{babel}
\usepackage[style=apa,sortcites=true,sorting=nyt,backend=biber]{biblatex}
\DeclareLanguageMapping{british}{british-apa}
% http://tex.stackexchange.com/questions/162212/initials-in-the-bibliography-firstinits-uniquename-not-working-correctly-in-bib
\DeclareSourcemap{
  \maps[datatype=bibtex]{
    \map{
       \step[fieldsource=sortname]
       \step[fieldset=namea, origfieldval, final]
    }
  }
}
\DeclareLabelname{
  \field{namea}
  \field{shortauthor}
  \field{author}
  \field{shorteditor}
  \field{editor}
  \field{translator}
}
\addbibresource{bibliography.bib}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage{amssymb,amsfonts,textcomp}
\usepackage{array}
\usepackage{hhline}
\usepackage{graphicx}
\usepackage[page,header]{appendix}
\usepackage{titletoc}

\usepackage[]{hyperref}
\hypersetup{
    bookmarksnumbered=true,     
    bookmarksopen=true,         
    bookmarksopenlevel=1,       
    colorlinks=true,            
    allcolors=blue,
    pdfstartview=Fit,           
    pdfpagemode=UseOutlines,    % this is the option you were lookin for
    pdfpagelayout=TwoPageRight
}
\usepackage[table]{xcolor}
\usepackage{cleveref}
\usepackage[textwidth=2cm,color=green,textsize=tiny]{todonotes}
\reversemarginpar
\usepackage{afterpage}
\makeatletter
\newcommand\arraybslash{\let\\\@arraycr}
\makeatother
\setlength\tabcolsep{1mm}
\renewcommand\arraystretch{1.3}
\newcounter{Figure}
\renewcommand\theFigure{\arabic{Figure}}
\title{The effects of attentional bias modification on rumination about current concerns: a case-series}
\shorttitle{The effects of ABM on rumination about current concerns}
\author{Paul Sharpe}
\affiliation{University of Exeter}
\leftheader{Attentional bias modification of rumination towards a self-relevant goal: A case-series}
\abstract{300 words max}
\authornote{I certify that all material in this dissertation \textbf{which
is not my own work} has been identified with appropriate acknowledgement
and referencing and I also certify that no material is included for
which a degree has previously been conferred upon me.}

\newcommand{\grswidth}{width=90mm}
\newcommand{\grsheight}{height=65mm}

\usepackage{amsmath,siunitx,caption}
\newcommand{\IE}[1][1]{% indent entry
  \hspace{#1em}\ignorespaces
}
\usepackage{mathtools}
\usepackage{csvsimple}

\usepackage{rotating}

% rotated table text
\usepackage{pifont}
\usepackage{booktabs}
\newcommand*\rot{\rotatebox{90}}

\begin{document}
\setlength{\marginparwidth}{1.5cm}
\todototoc
\listoftodos[Todo list]
\maketitle
\pdfbookmark{\contentsname}{toc}
%\tableofcontents
\startcontents[sections]
\printcontents[sections]{l}{1}{\setcounter{tocdepth}{2}}
\newpage
%\clearpage\setcounter{page}{1}

\todo{BODY: 8000 words max excluding toc, footnotes, tables, figures, references}
\todo{ABSTRACT use keywords (suggestion < 13)}
\todo{check draft against Monsell and Pinker}
\todo{Word count of main text on front page (latexcount.pl)}

\section{Introduction}

\subsection{Current state of anxiety and depression and treatments}

Mixed anxiety and depression is the most common mood disorder in
Britain \parencite{haliwell_fundamental_2007}. Its predicted growth
(World Health Organisation, 2001) makes the associated negative
individual and socio-economic consequences a global concern.
In depression, relapse is common and its likelihood increases steeply
with each depressive episode \parencite{haliwell_fundamental_2007}.
Anti-depressant medication (ADM) and psychological therapies for
depression such as CBT and MBCT can be effective, but patients often
dislike the side effects of ADM and there are high costs associated
with delivering psychological therapies.  Consequently, waiting times
in Britain currently average six to nine months, and can be as long as
two years \parencite{haliwell_fundamental_2007}.  There is a need for
cheap but effective interventions which target the cognitive mechanisms
\todo{introduce things before referring to them} underlying depression
and anxiety.

\subsection{What rumination is}

Rumination is a thought process consistently linked to both the onset and
maintenance of depression \parencite{watkins_habitgoal_2014}.  In their
review of the rumination literature, \textcite{smith_roadmap_2009}
note that rumination as a construct is robust but that ``there
is no unified definition [...] or standard way of measuring
it'' \textcite[][p. 117]{smith_roadmap_2009}.  To some extent,
worrying about the future has been associated with anxiety and is
distinguishable from brooding over the past which is more associated
with depression \parencite{papageorgiou_depressive_2004}.  However,
other accounts \parencite{watkins_comparisons_2005} suggest
that both types of rumination may share the key qualities of an
inability to control intrusive, repetitive thoughts in situations
where they are not constructive, but are nevertheless perceived to be
\parencite{watkins_constructive_2008}.  Rumination predicts symptoms of
both anxiety and depression \parencite{nolen-hoeksema_role_2000} and the
conditions are frequently comorbid \parencite{krusche_mindfulness_2013}.
Therefore, `repetitive negative thought' (RNT) may be a more useful
label which captures these similarities whilst distinguishing RNT from
the constructive role played by repetitive thought in problem solving
\parencite{watkins_constructive_2008}.

... the phenomenology of how adults \parencite{pearson_frequency_2008}
and young people \parencite{oliver_all_2015} experience rumination.

\subsubsection{worry}

Worry has been defined as \enquote{a chain of thoughts and
images, negatively affect-laden and relatively uncontrollable}
\parencite[][p. 10]{borkovec1983preliminary}.


\subsection{Theories of rumination}

Two theories of rumination have been influential.

\subsubsection{Response Styles Theory}

Response Styles Theory (RST) \parencite{nolen-hoeksema_responses_1991} defines
rumination as a particular response to depressed mood where a person
tends to focus on ``causes, consequences and symptoms of one's negative
affect'' \parencite[][p. 117]{smith_roadmap_2009}
 thereby prolonging low mood and depressive episodes.

\subsubsection{Control Theory}
 \parencite{martin_ruminative_1996} is broader than RST in that it explains
rumination as a thought process which arises when progress towards a
goal is perceived to be unsatisfactory, a state within which low mood
frequently co-occurs.

\textcite{watkins_habitgoal_2014} have sought to
unify these theories by proposing that RNT may be a habit, initiated
by goal discrepancies and subsequently cued by contingent contexts
such as mood or physical location.  They suggest that such automatic,
habitual responses come to depend on context more than the content
of particular unresolved goals, especially when contingent responses
involve passive focus on abstractly construed, negative content.

\subsection{Goals and current concerns}

\textcite[][p.249]{klinger_motivation_2011} define a current concern as
\enquote{the state of an organism between the time it becomes committed
to pursuing a goal and the time it either gains the goal or abandons
the pursuit.}

Explain how this relates to \textbf{motivation} and \textbf{cues}.
\todo{cf. \textcite{martin_ruminative_1996}}

\subsection{Koster's disengaement hypothesis}

\textcite{koster_understanding_2011} claim that cued repetitive
thought per-se is a normal cognitive response to self-evaluation,
but hypothesise that one driver of RNT, particularly brooding, is
an impaired attentional ability to disengage from negative thoughts
\textcite{koster_understanding_2011}.
\todo{signpost lack of demonstrating attentional engagement}

\subsection{Cognitive bias modification}

\subsubsection{CBM-I}

There is CBM-I ...

\subsubsection{CBM-A}

... but this is about CBM-A

\subsection{RAT}

Although it is resistant to change \textcite{watkins_habitgoal_2014},
it seems possible that habitual rumination could be altered using
counterconditioning techniques.  Counterconditioning is one of
the basic mechanisms which cognitive bias modification (CBM)
employs in the form of repetitive computer tasks to attenuate
attentional, interpretive and memory biases associated with
negative emotional states \parencite{hertel_cognitive_2011}.  Randomised
controlled trials indicate that CBM may be an effective treatment
for anxiety \parencite{hakamata_attention_2010} and depression
\parencite{yang_attention_2015}.  Attentional bias modification (ABM)
is a common form of CBM training in which participants use a computer
task to repeatedly attend towards or away from a particular stimulus such
as negatively valenced words or pictures \parencite[see][for a recent
review]{macleod_attentional_2015}.  This type of training resembles the
counterconditioning mechanism which \textcite{watkins_habitgoal_2014}
 suggest may reduce RNT.  A recent randomised controlled trial
of ABM on individuals with depressive symptoms
\parencite{yang_attention_2015} met the independent, but
essential criteria of a successful ABM intervention stressed by
\textcite{macleod_attentional_2015}.  First, a post-training
change in attentional bias was demonstrated.  Second,
and notable in the context of the habit-goal framework, this
effect on reducing depressive symptoms was mediated by rumination
\parencite{yang_attention_2015}. \textcite{yang_attention_2015} used
laboratory-based ABM training using sad word stimuli.  The proposed
study aims to extend these findings by testing whether ABM reduces
RNT and elevates mood in non-depressed, high ruminators exposed to
abstract, negative, ideographic cue words associated with an incomplete
self-relevant goal.  This is a novel and more direct test of RNT within
the habit-goal framework \textcite{watkins_habitgoal_2014}, as this
arrangement should create a context likely to trigger RNT within which
the counterconditioning effects of ABM training can be measured.

\subsection{Hypotheses}

Because the 
Anxiety and depression were measured due to their close association, and
uncertainty whether the procedure would affect brooding \todo{brooding
is a subtype of past-focussed rumination?} worry or both.

Reduced attentional bias, state rumination, state anxiety and low mood
scores are predicted after ABM training (phase B) in comparison with
baseline (phase A) measures.  Initial measures of trait rumination, trait
anxiety and depression are also predicted to reduce after ABM training.
Positive findings would add weight to the impaired disengagement
hypothesis \textcite{koster_understanding_2011} and the habit-goal
framework \textcite{watkins_habitgoal_2014} and would be proof of
principle for a potential clinical application of ABM to change RNT.

\section{Method}

\subsection{Design}

The current study included a novel use of ABM training towards an
ideographic current concern, and required a small number of participants
to undertake long-term training. To balance the exploratary nature
of the research with the ability to make statistical inferences
from the results we chose a randomized, single-case series design
\parencite{bulte_r_2008}. This was an AB phase design in which
baseline (A) measures were compared against intervention (B) measures
\parencite{bulte_r_2008}.

Randomization is a nonparametric approach which allowed us to make
statistical inferences for each individual participant.  In an AB phase
design, the sequence (baseline followed by intervention) is fixed,
therefore it is the point at which phase A transitions to phase B
which is randomized. Under the null hypothesis, a test statistic
for a particular set of observations would not differ regardless of
where the transition from A to B occurs. Randomisation tests hold the
observations constant and calculate the test statistic for all possible
transition permutations. Once sorted, the ${p}$ value is the proportion
of test statistics greater than or equal to the observed test statistic
\parencite{onghena_customization_2005}.

Based on previous research \parencite{yang_attention_2015}, 8 ABM
sessions (phase B) were considered necessary in order to detect
training effects. With a minimum of 8 measurement times (MTs) in phases
A and B, and a total of 35 MTs there were 20 possible transition
points between phases A and B. This allowed significance testing
at the ${p}$=.05 level for each participant completing all sessions
\parencite{onghena_customization_2005,bulte_r_2008}.

\subsection{Participants}

Participants were recruited  using the University of Exeter school of
Psychology research participation system, on-campus posters, departmental
email lists and Facebook groups linked to the University. People
were invited to evaluate a computer-based task with the potential to
reduce rumination towards an unresolved problem of their own choosing.
A maximum payment of {\pounds}20 was offered to participants who completed
all 35 sessions. Participants had to be fluent in English, have normal,
or corrected to normal vision, have access to a home computer running
Windows, Macintosh (OS X 10.9 or later), or Linux operating systems,
and not concurrently undergoing psychotherapy or taking psychotropic
medication.

Screening instruments were created using Lime Survey
\parencite{limesurvey} and completed using a web browser. Inclusion
criteria were a PHQ-8 \parencite{kroenke_phq8_2009} score {\textless}
11, to exclude people with mild depression or above, \todo{PHQ-8 >= 10
vs. PHQ-9 < 11 \parencite{wahl_standardization_2014}} and, to include
high trait ruminators or trait worriers, a Ruminative Responses Scale
(RRS) \parencite{treynor_rumination_2003} score ${\geq}$ 53 or a Penn
State Worry Questionnaire (PSWQ) \parencite{meyer_development_1990}
score ${\geq}$ 55. The RRS and PSWQ cut points were calculated to place
participants in the top 33\% of these measures, based on a sample
of 210 University of Exeter undergraduate students measured on RRS
(${M}$ = 46.9, ${SD}$ = 12.7) and PSWQ (${M}$ = 48.2, ${SD}$ = 14.9)
\parencite{moberly_controlled_2015}.

Figure \ref{flowchart} summarises the recruitment procedure. Of the
15 people (12 female), who met the screening criteria and offered to
participate, 6 were members of staff, 5 were postgraduate students,
2 were undergraduate students, 1 was a recent graduate, and 1 was the
partner of an undergraduate student. The mean age of participants was
31.38 years (${SD}$ = 9.99 years).

\begin{figure}[!h]
  \centering
  \includegraphics[width=140mm]{/home/paul/Documents/psychology/msc/M210/apprenticeship/dissertation/figure/recruitment.png}
  \caption{Recruitment flowchart}
  \label{flowchart}
\end{figure}

\subsection{Measures and Materials}

All survey instruments were created using Lime Survey
\parencite{limesurvey} and completed using a web browser (see
\cref{app:surveys}).

\todo{See McKay (2005) for examples of what each measure measures i.e. a bit more narrative}

\subsubsection{Dot-probe task}

The dot-probe task is commonly used to measure attentional bias,
based on differences in response times to pairs of stimuli
with differing affective valence, such as negative and neutral
word pairs \parencite{macleod_attentional_1986}. Our study used
word-pair stimuli (see figure \ref{fig:dotprobe}) and was based
on \textcite{yang_attention_2015}. We used two sets of visual word
stimuli in the dot-probe task. A set of Negative-Neutral (N-word)
pairs based on affective norms \parencite{citron_how_2014}, and a set
of Ideographic-Neutral (I-word) pairs associated with a current concern
chosen by each participant.

\begin{figure}[!ht]
  \centering
  \includegraphics[width=200mm,height=150mm]{/home/paul/Documents/psychology/msc/M210/apprenticeship/dissertation/dot_probe_kb.pdf}
  \caption{Example dot-probe trial for a right-handed participant,
  in which the negative word (\textsf{USELESS}) appears at the upper
  location, and the neutral word (\textsf{WHISPER}) appears at the
  lower location.  Correct responses are shown for a subsequent probe
  appearing at either the upper or lower location.}
  \label{fig:dotprobe}
\end{figure}

\todo{RAT: 1250ms exposure. Nick \enquote{On the basis of Mogg/Bradley's papers, I think 1000 ms is justified, and you could
perhaps stretch it to 1250 ms just to be extra-sure that you are capturing the maintenance of attention.} see email and
\textcite{mogg_attentional_2005} }

Each trial began with an 25 x 25 pixel (7 pixel thick) white fixation
cross centred on a black screen. After 500ms, this was replaced by a word
pair from the current stimulus set.  One word from the pair appeared
above the fixation cross location and one below. Word pairs were 125
pixels high with a vertical space between the upper and lower words such
that the stimuli subtended a visual angle of approximately 2$^{\circ}$
\footnote{This angle was calculated using a height measurement of the
visible area of each participant's computer display, and the assumption
that participants followed the instruction to sit approximately 60cm from
the screen.}. Neutral words occurred with equal frequency at the upper
or lower positions. After 1250 ms, the word pair was replaced by either
a greater than (\texttt{>}) symbol or less than (\texttt{<}) symbol at a
random letter location within one of the previous word locations. Probes
appeared with equal frequency at upper and lower locations. The only
valid keyboard responses were greater than (\texttt{>}) and less than
(\texttt{<}). The probe remained on the screen until the participant
pressed a valid key. A correct response was recorded if the keypress
matched the probe symbol. There was no feedback for incorrect responses. A
blank screen with a random inter-trial interval (ITI) between 100-500ms
followed each trial. Participants were instructed to respond as quickly
and accurately as possible.  Each dot-probe block consisted of 96 trials
and took approximately 5 minutes to complete.

The task was developed using OpenSesame, an open-source experiment builder
for the social sciences \parencite{mathot_opensesame_2011}. OpenSesame
was chosen as a package which was relatively easy to install on Windows,
Macintosh (OSX ${\geq}$ 10.9) and Linux operating systems, thereby
eliminating any dependencies on a webserver for software development or
data collection. Installation instructions for were created using screen
capture software and uploaded to YouTube.

\subsubsection{Attentional Bias Modification task}

The Attentional Bias Modification (ABM) task used the same paradigm as the
dot-probe task but was designed modify, rather than measure attentional
bias. As such, it differed in three respects. First, there were double
the number (192) trials in each block. Second, only N-word pairs were
used as stimuli. Finally, probes in ABM trials always appeared at the
neutral word location. Thus, responses required repeated orientation of
attention away from the negative word in the pair. Each ABM block took
approximately 15 minutes.

\subsubsection{Pre--Post Measures}

The following measures were taken before and after the dot-probe/ABM
training intervention.

\paragraph{RRS}

The Ruminative Responses Scale (RRS) is a 22 item measure of
trait rumination, with item scores ranging from 1--4. The RRS is
valid and reliable, having an expected Cronbach's $\alpha$ of .85
\parencite{treynor_rumination_2003}. Questions on the RRS were asked
in relation to the previous 4 weeks, to correspond approximately with
the month before the study (pre) and time within the study (post)
(see \cref{app:surveys}).

\paragraph{GAD-7}

The GAD-7 is a 7 item measure of Generalised Anxiety Disorder (GAD),
with items relating to the previous 2 weeks, and scores ranging from
0--3. The GAD-7 is an efficient, internally reliable (Cronbach's $\alpha$
> .85) tool for assessing GAD severity in clinical research, with good
test-retest reliability \parencite{spitzerrl_brief_2006}.

\paragraph{PHQ-9}

The 9 item Patient Health Questionnaire Depression (PHQ-9) is a brief,
reliable (Cronbach's $\alpha$ > .85) and valid measure of depression
severity \parencite{kroenke_phq9_2001}. Item scores range from 0--3,
and questions relate to the previous 2 weeks.

\paragraph{PSWQ}

The 16 item Penn State Worry Questionnaire (PSWQ) is an internally
consistent measure of trait worry with good test-retest reliability
\parencite{meyer_development_1990}.  Item scores range from 1--5.

\subsubsection{Daily Measures}

The following measures were taken approximately every 24 hours, except
where sessions were postponed.

\paragraph{Attentional bias}

Attentional bias was measured using using the dot-probe task. After
removing inaccurate trials or those with response times (RTs)
exceeding 3 standard deviations beyond the mean, attentional bias
scores were calculated from the remaining RTs using the equation
\begin{equation}
  Attentional\ bias\ score = [(NuPl + NlPu) - (NuPu + NlPl)]/2\label{eq:1}
\end{equation}
where ${N}$ = Negative word, ${P}$ = Probe, ${u}$ =
upper, ${t}$ = lower \parencite{bradley_attentional_1997}.
A bias towards negative words is reflected in longer latencies for
probes at the opposite location (left-hand side of equation \eqref{eq:1})
and shorter latencies for probes at the same location (right-hand side
of equation \eqref{eq:1}). Therefore, more positive scores reflect an
attentional bias towards (i.e. vigilance for) negative words relative
to neutral words, whereas more negative scores indicate avoidance
\parencite{bradley_attentional_1997}.

\paragraph{GRS}

The Goal Rumination Scale (GRS) is a 7 item measure of state rumination
towards a specific problem \parencite{schultheiss_role_2008}.  Item scores
range from 1--7, with items 5--7 reversed. Reliability of the GRS is
good (Cronbach's $\alpha$ = .87), based on a single sample of $N$ =
101. Questions on the GRS -SF were asked in relation to the last 24 hours.

\paragraph{PANAS-SF}

The 10 item, short form Positive and Negative Affect Schedule (PANAS-SF)
\parencite{mackinnon_short_1999} measures positive affect (Cronbach's
$\alpha$=.78) and negative affect (Cronbach's $\alpha$=.87). Item scores
range from 1-5.  Because we were specifically interested in changes in
depression and anxiety, we added 4 items to the PANAS-SF.  Items `sad' and
`depressed' were chosen as a state measure of depression, the rationale
being that they would correlate negatively with PA and positively with NA.
Items `anxious' and `worried' were added as a state measure of worry
\todo{I need to have committed to anxiety or worry by this point!} as they
were expected to correlate positively with NA. \todo{need a reference
to show lack of items at low end of PA and that low PA/high NA ==
depression.} Questions on the PANAS-SF were asked in relation to the last
 24 hours.

\subsubsection{N-word pairs}

The Sussex Affective Word List (SAWL) \parencite{citron_how_2014} was
used to create 66 N-word stimulus pairs. Starting with 66 words rated
most negative and most neutral, pairs were created by matching words
of equivalent character length, drawing additional words from the SAWL
as necessary to ensure that all pairs were matched on length. A small
number of pairs which appeared to be semantically related were adjusted
by replacing the neutral word in the pair with an alternative from
the SAWL.  Independent samples t-tests showed significant differences
for mean ratings of valence and arousal (${P}$s {\textless} .001).
Pairs were matched for frequency, imageability, familiarity, number of
characters and number of syllables (all ${P}$s {\textgreater} .16) (see
\cref{app:nwordttests}). In addition, the mean valence between members
of any pair was at least 1.44 (Mean: 2.15, ${SD}$ = 0.37). To form the
stimulus blocks, pairs were ranked by descending mean valence difference.
The 6 pairs with the lowest difference were assigned to the ``spare''
block.  The remaining 60 pairs were divided at every 10 word boundary,
forming 6 groups. Each experimental block of 6 words was created by
taking the top pair from each group, until all groups were exhausted,
thereby creating 10 blocks with a mixture of valence differences. The
complete N-word list can be seen in \cref{app:nwordlist}

\subsubsection{I-word pairs}
\label{sec:iwordpairs}

We refer to ideographic words (I-words) as the set of 6 words chosen
by each participant for their likelihood to induce rumination
about the participant's chosen current concern.

Due to the unpredictability of these words, and the limited number of
words in the SAWL \parencite{citron_how_2014}, a larger data set was
required to matched pairs to I-words. A database of neutrally valenced
words was created including frequency, imageability, familiarity, word
length and number of syllables attributes from the MRC psycholinguistic
database \parencite{wilson_mrc_1988}. A separate table was added to the
database containing 1030 word valence means from the Affective Norms
for English Words (ANEW) dataset \parencite{bradley_affective_1999}.

Two different matching approaches were used, depending on whether
each I-word word was present in, or absent from, the MRC database.
If present, a neutral pair was selected from a pool of words having
a frequency {\textpm}15\% that of the I-word, an ANEW valence mean
(range 1-9) between 4.00 and 6.00 and an equal number of characters.
After selecting a pool of matched words on the preceding criteria, a
best match was found by inspection of candidate words based on number
of syllables, imageability and familiarity.  Some I-words, such as
long words or high frequency words, could not be matched using these
criteria due to lack of available data. In these cases, a word with the
most neutral valence was chosen that also minimised differences in length
and frequency between the word pair. I-words absent from the MRC database
(including proper nouns) were paired with words selected from a pool of
56 words having a frequency of 1 (on the assumption that words missing
from the database would most likely be of low frequency), and for which
an ANEW valence rating was available.  A word was selected from this pool
having an ANEW valence mean between 4.00 and 6.00 and an equal number
of characters to the I-word. If an I-word or its pair was a member of
the N-word set, that N-word pair was substituted with the next available
pair from the spare N-words block with the largest difference in valence.

Each participant's I-word pairs etc. are shown in \cref{sec:iwordlist}

\subsection{Procedure}

People who met the screening criteria and accepted the invitation to
participate, met the researcher at the University of Exeter to complete
the initial 1 hour preparatory session. Participants gave informed,
written consent, in line with the guidelines set by the University
of Exeter School of Psychology Ethics Committee.  Following this they
completed baseline measures for RRS, PHQ-9, GAD-7 and PSWQ using a web
browser and Lime Survey \parencite{limesurvey}.

Next, using a procedure based on \textcite{roberts_cueing_2013}, the
participant was instructed to select an unresolved current concern (see
\cref{sec:iwordinstructions}), and rated their concern on a 5 item scale,
with each item in the range 1--9 \cref{app:concernrating}. The concern
was accepted if ratings for the questions \enquote{How much you have
been thinking about it over the last week?} and \enquote{How much does
it bother you now?} were > 5, and the concern was unlikely to resolve
within the following 5 weeks. All participants' initial concern met
these criteria. Participants wrote a short statement summarising their
concern and recorded the length of time that it had been bothering them.

The participant then generated their ideographic words (I-words). They
were instructed to generate up to 10 English words, excluding
phrases, associated with their concern. When choosing these words,
they were asked to consider \enquote{causes, meanings and implications}
\parencite[][p.55]{watkins_concreteness_2009} relating to their concern,
thereby encouraging abstract construal, which has been associated with
rumination \parencite{watkins_concreteness_2009}. From their list,
they then chose the 6 words most likely to cause them to ruminate about
their concern.

To familiarise themselves with the dot-probe task, participants then
completed a practice block consisting of N-word block 7 and a set of
I-word pairs generated by the experimenter. Whilst this was underway, the
experimenter validated the participant's I-words, noting any which known
to be difficult to match with a pair from the neutral word database. These
including plurals, acronyms, hyphenated words, words with stems related
to an N-word or words longer than 10 characters. After completing the
practice block, participants were instructed to replace any invalid
words with synonyms or wth alternatives from their list, where these
were available. Care was taken to ensure that the semantics of any
adjusted words were chosen by the participant without influence from
the experimenter (see \cref{sec:iwordinstructions}). All participants
successfully generated 6 I-words. They rated the valence of each word in
relation to their concern on a 7-point scale, using instructions based
on \textcite{citron_how_2014}. Participants then completed a distraction
task for 5 minutes (see \cref{app:distraction}).

Participants were given an information sheet to help them install and
complete the computer task (see \cref{app:taskinstructions}). As a
motivational aid, they were also given a printed calendar on which to
plan their daily sessions and cross them off when completed. To further
encourage completion, they were instructed to write an implementation
intention on the calendar indicating an approximate time when they would
complete each session. If reqested, the experimenter installed OpenSesame
\parencite{mathot_opensesame_2011} on the participant's laptop. The
initial session ended with the experimenter and participant agreeing a
time on the same or the following day when the experimenter could be
available to support the participant whilst installing the computer
task on their own computer and completing their first session. All
participants successfully completed the preparatory session (see
\cref{app:initialsession} for full details of the session protocol).

The experimenter then prepared the experiment and associated data
files required for the participant to run the computer task. The data
files consisted of the I-word pairs (\cref{sec:iwordpairs}) which
were validated by the experimenter's supervisor, the N-word pairs,
the participant's randomization schedule (generated using the command
\texttt{selectdesign(design=AB,MT=35,limit=8)} from the \texttt{SCRT}
package \parencite{bulte_r_2008}), a stimulus configuration file and a
configuration file to position stimuli based on the participant's screen
height. These files were emailed to the participant for them to install.

\subsubsection{Daily Sessions}

Participants were instructed to complete all experimental sessions on a
computer at their home. Each day, the experimenter sent participants a
templated email containing instructions on how to complete the session
(see \cref{app:reminder}). For the first session, additional instructions
included a link to the installation video on YouTube. Participants
began each session by completing the dot-probe task (phase A) or the ABM
training, followed by the dot-probe (phase B). Using a web browser, they
then used Lime Survey to upload their task data, record whether their
conern was still unresolved and complete PANAS-SF and GRS measures. On
a daily basis, the experimenter recorded whether each participant
had completed a session and, if so, their accuracy on the task. The
experimenter periodically sent additional emails to motivate participants
by notifying them of their progress, to ensure their well-being if 3
consecutive sessions were skipped, and to prepare them for the slightly
longer task when transitioning to phase B. From session 25 onwards,
sessions ended with a message informing the participant of the amount
they had earnt so far. Participants provided post-intervention RRS,
PHQ-9, GAD-7 and PSWQ measures using the Lime Survey website within
12 hours of completing the final session. On exiting the study, all
participants were emailed debrief information \cref{app:debrief} and
information about sources of support \cref{app:support} and were paid
for their participation.

\subsubsection{Stimulus allocation}

The total of N word pairs allowed for 1 practice and 36 experimental
dot-probe test sessions even when the 18 G set words fully overlap
with P set words.  Dot-probe and ABM tasks will be developed using
OpenSesame \parencite{mathot_opensesame_2011} and measurement instruments
administered online using Lime Survey \parencite{limesurvey}.

\textcite{see_reduction_2009} point out that the strongest claims come
from detecting a ${general}$ change in attentional bias in relation
to emotional valence, rather than to a change in bias to specific
stimuli. To maximise both the measurement and modification of attention
to emotional tone in general, each assessment block will only contain
stimulus materials not previously exposed in any preceding training
block \textcite{see_reduction_2009}. Table 1 provides an example of
how subsets of the P and G sets will be introduced as the experiment
progresses. Dot-probe blocks will always consist of 5 word pairs;
the next 4 pairs from the P set and 1 pair from the G set. The G pair
will change to the next highest rated pair every 2 blocks.  To maximise
stimulus variety during ABM, these blocks will include word pairs from all
preceding dot-probe blocks. Thus, the number of stimulus word pairs will
increase with each ABM block. To emphasise ideographic stimuli, G pairs
will appear twice as frequently as P pairs. Each word in the pair will
appear with equal frequency at upper and lower screen locations. Where
necessary, stimuli will be randomly excluded from a stimulus subset
until the total exposures for the block is exactly divisible by the
stimulus subset.

To keep people completing sessions when they unexpectedly lose access
to their initial computer (go on holiday, etc.) I allowed them
to install the task on multiple machines and carry out the task in
different locations.  I'll mention this for the participants I know
needed to do this.

\todo{stimulus allocation table}

\section{Ethical Considerations}

Because screening measures were submitted remotely, depression was
measured using the PHQ-8 which omits one item measuring suicidal ideation.
Anyone scoring ${\geq}$ 10 on the PHQ-8 \parencite{kroenke_phq8_2009}
received practical, supportive information about resources available
to people who may be suffering from depression. The researcher
completed training in implementing the latest risk protocol employed
by the University of Exeter, Mood Disorders Centre. Risk cover by a
clinically trained member of staff was arranged in advance of each PHQ-9
(which includes a suicidal ideation question) that was administered to
participants. No participants triggered the risk protocol.

A potential risk of harm was identified arising from increasing
rumination in high trait ruminators, along with the burden of a long
testing period. The experimenter mitigatated this risk by keeping in
regular contact with participants, notably when more than two testing
sessions were skipped. Any concerns were raised with the researcher's
supervisor. On leaving the study, all participants were emailed a copy
of the support information for people who may suffer from depression.

Participants were not identifiable from their electronic data. Online
measures were stored on a secure digital filing system and all other
data on a memory stick. Any sensitive written information was stored in
a locked filing cabinet.

A detailed ethical submission was approved by the University of Exeter,
School of Psychology Ethics Committee (see \cref{app:ethics}).

\section{Analyses}
\label{analyses}

Done using R (list packages).

<<power, echo=FALSE, error=TRUE>>=
library(pwr)
library(stringr)
format_power <- function(x) {
  x <- sprintf("%0.2f",x)
  str_replace(as.character(x), "^0\\.", ".")
}

# RRS d=.49 (Yang et al., 2015)
rrs_pwr <- pwr.t.test(d=.49,n=12,sig.level=0.05,type="paired",alternative="two.sided")
rrs_pwr <- format_power(rrs_pwr$power)

# BDI-II d=1.50 (Yang et al., 2015)
bdi_pwr <- pwr.t.test(d=1.5,n=12,sig.level=0.05,type="paired",alternative="two.sided")
bdi_pwr <- format_power(bdi_pwr$power)

# STAI-T d=.88 (Yang et al., 2015)
stai_pwr <- pwr.t.test(d=.88,n=12,sig.level=0.05,type="paired",alternative="two.sided")
stai_pwr <- format_power(stai_pwr$power)

# PSWQ d=.51 (Enock & Hofmann, 2014)
pswq_pwr <- pwr.t.test(d=.51,n=12,sig.level=0.05,type="paired",alternative="two.sided")
pswq_pwr <- format_power(pswq_pwr$power)
@

\subsubsection{Pre--Post Measures}

Paired samples t-tests were used to compare participants' pre
and post ABM training measures of rumination (RRS), depression
(PHQ-9), anxiety (GAD-7) and worry (PSWQ). Using a similar ABM
procedure, \textcite{yang_attention_2015} found significant post
training reductions in rumination, using RRS (${d}$=.49), depression,
using BDI-II \parencite{beck_manual_1996} (${d}$=1.50) and anxiety, using
STAI-T \parencite{spielberger_manual_1983} (${d}$=.88). Given these effect
sizes, 12 participants and $\alpha$ set at .05, two-tailed calculations
of power (1-$\beta$) gave \Sexpr{rrs_pwr} for RRS, \Sexpr{bdi_pwr}
for BDI-II and \Sexpr{stai_pwr} for STAI-T. In practice, these are
likely to be lower as participants in \textcite{yang_attention_2015}
were undergraduates with mild to severe depression in contrast with
the current study where participants with mild depression or above were
excluded. Estimates could also vary due to the different instruments used
to measure depression (PHQ-9) and anxiety (GAD-7) in the current study. In
an ABM training study using smartphones, \textcite{enock_attention_2014}
found a significant post ABM training reduction in PSWQ (${d}$=.51) using
a dot-probe task with neutral and disgust face stimuli. A two-tailed
calculation with 12 participants and $\alpha$ set at .05, gave power
(1-$\beta$) of \Sexpr{pswq_pwr}. In summary, the current study is likely
to be sufficiently powered to detect changes in depression (PHQ-9) and
possibly anxiety (GAD-7), but underpowered to detect changes in rumination
(RRS) and worry (PSWQ).

\subsubsection{Daily Measures}

Comparisons were made between each participant's baseline (phase A)
scores and their post-training (phase B) scores

All questions on the daily outcome measures were mandatory on the online
survey, so there was no missing data for any completed survey.
and, using meta-analysis, across all participants
and a meta-analysis across all participants.
\cite[][p.64]{onghena_customization_2005} describe the theory behind this use of meta-analysis

Sentence/quote on how this works in genereral, then ...

Given the lack of power for some pre-post ... measures The main analyses were the daily measures ...Visual analyses of each
outcome measure was planned using graphs generated by the R package
'SCVA' \parencite{bulte_when_2012}.  Inferential statistics and effect
sizes (PND) comparing A and B phases for measures of attentional bias
(I-words and N-words), state rumination (GRS) and mood (I-PANAS-SF) was
calculated for each case using nonparametric randomisation tests provided
by the R package 'SCRT' \parencite{bulte_r_2008}.

Of the items added to the PANAS-SF, `sad' and `depressed' correlated
strongly with each other and weakly with PA items on the scale, whereas
`anxious' and `worried' were moderately associated with NA, but not as
highly as NA scale itself (see \cref{app:mood}). Given that PANAS is an
established measure, but is known to be poor at measuring depressed mood
we analysed three mood variables: positive affect (PA scale), negative
affect (NA scale) and `depression' (`sad' and `depressed' items).

A meta-analysis for each outcome across all participants was carried
out using the R package 'SCMA' \parencite{bulte_singlecase_2013}.

"additive method is shown to be more powerful than the multiplicative method, having
a greater probability than the multiplicative method of yielding significant
results when there actually are treatment effects." \parencite{edgington_additive_1972}

\todo{Comment on why there are no multiple comparisons corrections}

\section{Results}

<<screening, echo=FALSE, error=TRUE>>=
screening<-read.csv('/media/paul/2E95-1293/study/screening.csv',header=TRUE)
@

At screening, the 15 participants who began the study had a mean PHQ-8 score of \Sexpr{sprintf("%0.2f",mean(screening$phq8total))}
(${SD}$=\Sexpr{sprintf("%0.2f",sd(screening$phq8total))}), a mean RRS score of \Sexpr{sprintf("%0.2f",mean(screening$rrstotal))}
(${SD}$=\Sexpr{sprintf("%0.2f",sd(screening$rrstotal))}), and a mean PSWQ score of \Sexpr{sprintf("%0.2f",mean(screening$pswqtotal))}
(${SD}$=\Sexpr{sprintf("%0.2f",sd(screening$pswqtotal))}). There were no outliers (> 3SD) on these measures.

\todo{(calculate) M/SD dot-probe accuracy}
No participants fell below the accuracy threshold for checking/exclusion.

\todo{visual representation of completion, sessions skipped, accuracy}

Three participants withdrew from
the study. One person withdrew before completing any sessions due to
concerns that the study would worsen their social anxiety. One person
was unable to commit enough time to the study after 5 sessions. The third
had completed 24 sessions when a holiday meant that they would be unable
to complete sufficient phase B sessions.

\todo{Predictability in relation to screening measures
"Looking at the scores from these participants they were typical/atypical."
}

P16 didn't complete GRS and PANAS for session 8 but told me scores were
the same as for session 7.
Bad dot-probe data for p7 session 32 so session omitted from analysis.

no problems resolved

\input{results/completed.tex}

\subsection{Pre/Post Measures}

<<external, cache=FALSE, echo=FALSE>>=
knitr::read_chunk('../opensesame/dotprobe/prepost.R')
knitr::read_chunk('../opensesame/dotprobe/analyse.R')
knitr::read_chunk('../opensesame/dotprobe/nwords.R')
knitr::read_chunk('../opensesame/dotprobe/iwords.R')
@

<<prepost, results='asis', echo=FALSE, error=TRUE>>=
@
\todo{Outliers > 3SD on pre (and post?)}
\todo{How to indicate the CIs are pre-post difference e.g. "The only scale on which Ps showed a significant difference was ...  All others were NS"}
\todo{Description of table pointing out sig. and NS differences}
\todo{Check understanding of CIs}

\todo{Point out that these are trait measures.}


\subsection{Visual Analysis}

... but now we can look at things individually, visually

\todo{Will present each participant's day by day data.  This allows you to analyse things visually.  Explain what people look for (cite): variability within each phase, change from A to B, trend in baseline that complicates interpretation ...  This is what to look out for ...}

\todo{Do it for each outcome.  Probably not much more than a couple of sentences for each.  Mainly a synthesis across Ps (patterns), but possibly draw attention to outliers.}

\subsubsection{Attentional bias N-words}

\begin{figure}[!ht]
\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/5/p5_n.jpg}
\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/6/p6_n.jpg}
\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/7/p7_n.jpg}
\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/8/p8_n.jpg}
\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/9/p9_n.jpg}
\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/10/p10_n.jpg}
\caption{Attentional bias scores for N-words (participants 5--10)}
\end{figure}

Description of these graphs.

\clearpage
\begin{figure}[!h]
\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/11/p11_n.jpg}
\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/12/p12_n.jpg}
\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/15/p15_n.jpg}
\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/16/p16_n.jpg}
\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/18/p18_n.jpg}
\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/19/p19_n.jpg}
\caption{Attentional bias scores for N-words (participants 11, 12, 15, 16, 18 and 19)}
\end{figure}

Description of these graphs.

\subsubsection{Attentional bias I-words}

\begin{figure}[!ht]
\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/5/p5_i.jpg}
\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/6/p6_i.jpg}
\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/7/p7_i.jpg}
\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/8/p8_i.jpg}
\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/9/p9_i.jpg}
\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/10/p10_i.jpg}
\caption{Attentional bias scores for I-words (participants 5--10)}
\end{figure}

Description of these graphs.

\clearpage
\begin{figure}[!h]
\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/11/p11_i.jpg}
\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/12/p12_i.jpg}
\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/15/p15_i.jpg}
\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/16/p16_i.jpg}
\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/18/p18_i.jpg}
\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/19/p19_i.jpg}
\caption{Attentional bias scores for I-words (participants 11, 12, 15, 16, 18 and 19)}
\end{figure}

Description of these graphs.

\subsubsection{GRS}

\begin{figure}[!ht]
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/5/p5_grs.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/6/p6_grs.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/7/p7_grs.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/8/p8_grs.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/9/p9_grs.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/10/p10_grs.jpg}
\caption{GRS scores (participants 5--10)}
\end{figure}

Description of these graphs.

\clearpage
\begin{figure}[!h]
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/11/p11_grs.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/12/p12_grs.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/15/p15_grs.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/16/p16_grs.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/18/p18_grs.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/19/p19_grs.jpg}
\caption{GRS scores (participants 11, 12, 15, 16, 18 and 19)}
\end{figure}

Description of these graphs.

\subsubsection{PA}

\begin{figure}[!ht]
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/5/p5_pa.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/6/p6_pa.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/7/p7_pa.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/8/p8_pa.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/9/p9_pa.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/10/p10_pa.jpg}
\caption{PA scores (participants 5--10)}
\end{figure}

Description of these graphs.

\clearpage
\begin{figure}[!h]
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/11/p11_pa.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/12/p12_pa.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/15/p15_pa.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/16/p16_pa.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/18/p18_pa.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/19/p19_pa.jpg}
\caption{PA scores (participants 11, 12, 15, 16, 18 and 19)}
\end{figure}

Description of these graphs.

\subsubsection{NA}

\begin{figure}[!ht]
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/5/p5_na.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/6/p6_na.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/7/p7_na.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/8/p8_na.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/9/p9_na.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/10/p10_na.jpg}
\caption{NA scores (participants 5--10)}
\end{figure}

Description of these graphs.

\clearpage
\begin{figure}[!h]
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/11/p11_na.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/12/p12_na.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/15/p15_na.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/16/p16_na.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/18/p18_na.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/19/p19_na.jpg}
\caption{NA scores (participants 11, 12, 15, 16, 18 and 19)}
\end{figure}

Description of these graphs.

\subsubsection{'Depression'}

\begin{figure}[!ht]
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/5/p5_d.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/6/p6_d.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/7/p7_d.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/8/p8_d.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/9/p9_d.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/10/p10_d.jpg}
\caption{Depression ('sad'+'depressed') scores (participants 5--10)}
\end{figure}

Description of these graphs.

\clearpage
\begin{figure}[!h]
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/11/p11_d.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/12/p12_d.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/15/p15_d.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/16/p16_d.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/18/p18_d.jpg}
\includegraphics[width=90mm,height=70mm]{/media/paul/2E95-1293/study/participants/19/p19_d.jpg}
\caption{Depression ('sad'+'depressed') scores (participants 11, 12, 15, 16, 18 and 19)}
\end{figure}

Description of these graphs.

%\subsubsection{GRS}
%\begin{figure}[!ht]
%\includegraphics[]{grs.jpg}
%\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/7/p7_i.jpg}
%\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/7/p7_n.jpg}
%\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/7/p7_grs.jpg}
%\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/7/p7_panas.jpg}
%\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/1/p1_grs.jpg}
%\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/8/p8_grs.jpg}
%\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/7/p7_grs.jpg}
%\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/8/p8_grs.jpg}
%\includegraphics[width=90mm,height=65mm]{../opensesame/dotprobe/mbd_grs_0.jpg}
%\includegraphics[width=90mm,height=50mm]{/media/paul/2E95-1293/study/participants/1/p1_grs.jpg}
%\includegraphics[width=90mm,height=65mm]{../opensesame/dotprobe/mbd_grs_1.jpg}
%\includegraphics[width=90mm,height=65mm]{../opensesame/dotprobe/mbd_grs_2.jpg}
%\includegraphics[width=90mm,height=65mm]{../opensesame/dotprobe/mbd_grs_3.jpg}
%\includegraphics[width=90mm,height=65mm]{../opensesame/dotprobe/mbd_grs_4.jpg}
%\includegraphics[width=90mm,height=65mm]{../opensesame/dotprobe/mbd_grs_5.jpg}
%\includegraphics[width=90mm,height=65mm]{../opensesame/dotprobe/mbd_grs_6.jpg}
%\caption{GRS scores for all participants\label{overflow}}
%\end{figure}

\subsection{Inferential Statistics}

<<inferentials, results='asis', echo=FALSE, error=TRUE>>=
@

\todo{Describe any patterns in each table, see \parencite{watkins_ruminationfocused_2007} including MA}

Ecological validity vs. pre/post measures: daily measures took place in real environment.

\section{Discussion}

\subsection{Does CBM-A work?}

\enquote{When anxiety and depression were examined separately,
CBM significantly modified anxiety but not depression. There was
a nonsignificant trend toward a larger effect for studies including
multiple training sessions.} \parencite{hallion_metaanalysis_2011}

\enquote{The therapeutic benefit of ABM is rather small for anxiety, while the amount of data
for other symptom categories is limited.} \parencite{mogoase_clinical_2014}

\subsection{vs. CBM-I}

\enquote{CBM had a medium effect on biases (g = 0.49) that was stronger
for interpretation (g = 0.81) than for attention (g = 0.29) biases} \parencite{hallion_metaanalysis_2011}

\subsection{moderators}

\enquote{The effects of ABM on attention bias were moderated by stimulus
type (words vs pictures) and sample characteristics (healthy vs. high
symptomatology).} \parencite{beard_efficacy_2012}

\enquote{Moderation analysis of the between-groups effect revealed
a significant effect for ABMT delivered in the clinic (d = 0.34, P =
0.01, CI = 0.07–0.62), and a nonsignificant effect for ABMT delivered
at home} \parencite{linetzky_quantitative_2015}

\subsection{rumination}

\enquote{Thus, people with high implicit motivation were less prone to ruminate
about their goals and people with high goal commitment were more likely
to ruminate. This effect was qual- ified by a marginally significant
goal commitment x implicit motivation effect, B = 0.319, SE = 0.177,
t(91) = 1.80, p = .07. As shown in Table 5, the interaction was due to a
damping effect of implicit motivation on goal rumination in low-commitment
participants.} \parencite{schultheiss_role_2008}

\begin{itemize}
\item Could individual's current concern(s) indicate the type of bias modification which might be beneficial?
\item ABM training other than the dot-probe Sigurjonsdottir et. al 2015
\item What is an effective dose?
\end{itemize}

\subsubsection{Limitations}

\begin{itemize}
\item self-report measures
\item Longevity of effects treatment? Would ABA revert?
\item What happens when problem resolves?
\item Only 2 measurement times (pre/post) vs. daily changes in AB, mood, rumination.
\end{itemize}

\paragraph{multiple baselines}

More specifically, this was an AB phase nonconcurrent multiple
baseline replication design across participants\todo{sure?!!}
\parencite{bulte_when_2012} \parencite{onghena_customization_2005}.
Didn't control for historical factors which you would
get if all participants started at the same time
\parencite{watson_nonconcurrent_1981}.

\printbibliography
%% CAVEAT: \appendices environment breaks \cleveref
\newpage
\appendix
\appendixpage

\setcounter{tocdepth}{2}
\startcontents[sections]
\printcontents[sections]{l}{1}
%\addappheadtotoc
%\todo{appendices: 4000 words max (~250 words/page i.e. 16 pages)}

\section{Survey Measures}
\label{app:surveys}

\begin{sidewaysfigure}[hp]
\includegraphics[width=270mm]{figure/rrs.png}
\caption{Ruminative Responses Scale (RRS) administered using Lime Survey}
\end{sidewaysfigure}

\begin{sidewaysfigure}[hp]
\includegraphics[width=250mm]{figure/gad7.png}
\caption{GAD-7 administered using Lime Survey}
\end{sidewaysfigure}

\begin{sidewaysfigure}[hp]
\includegraphics[width=250mm]{figure/phq9.png}
\caption{PHQ-9 administered using Lime Survey}
\end{sidewaysfigure}

\begin{sidewaysfigure}[hp]
\includegraphics[width=250mm]{figure/pswq.png}
\caption{Penn State Worry Questionnaire (PSWQ) administered using Lime Survey}
\end{sidewaysfigure}

\begin{sidewaysfigure}[hp]
\includegraphics[width=250mm]{figure/panas.png}
\caption{Positive and Negative Affect Schedule (PANAS-SF) administered using Lime Survey}
\end{sidewaysfigure}

\begin{sidewaysfigure}[hp]
\includegraphics[width=250mm]{figure/grs.png}
\caption{Goal Rumination Scale (GRS) administered using Lime Survey}
\end{sidewaysfigure}

\section{N-word stimulus pairs}
\label{app:nwordlist}

\begin{table}[!htbp]
{\tiny
  \begin{tabular}{cllllll}\hline%
    Block & Pair 1 & Pair 2 & Pair 3 & Pair 4 & Pair 5 & Pair 6\\\hline 
    \csvreader[late after line=\\]{../experiment/66_nwords.csv}{Block=\block}%
      {\block & \textsf{\csvcolii}-\textsf{\csvcoliii} & \textsf{\csvcoliv}-\textsf{\csvcolv} &
      \textsf{\csvcolvi}-\textsf{\csvcolvii} & \textsf{\csvcolviii}-\textsf{\csvcolix} &
      \textsf{\csvcolx}-\textsf{\csvcolxi} & \textsf{\csvcolxii}-\textsf{\csvcolxiii}}%
    \hline
  \end{tabular}
}
\end{table}

\section{N-word t-tests}
\label{app:nwordttests}

<<nwords, results='asis', echo=FALSE, error=TRUE>>=
@

\section{Distraction task}
\label{app:distraction}
\input{procedure/distraction.tex}

\section{Task instructions}
\label{app:taskinstructions}
\input{procedure/task_instructions.tex}

\section{I-word stimulus pairs}
\label{sec:iwordlist}

<<iwords, results='asis', echo=FALSE, error=TRUE>>=
@

\section{Current Concern Rating Scale}
\label{app:concernrating}

\section{Unresolved goal and I-word generation instructions}
\label{sec:iwordinstructions}
% FIXME: remove supertablular nonsense
%\input{procedure/iwords.tex}

\section{Initial Session Protocol}
\label{app:initialsession}

\section{Example session reminder email}
\label{app:reminder}
\input{procedure/reminder.tex}

\section{Debrief sheet}
\label{app:debrief}
\input{procedure/debrief.tex}

\section{Sources of support information sheet}
\label{app:support}
\input{procedure/support.tex}

\section{Ethical Approval}
\label{app:ethics}

\begin{figure}[hp]
\includegraphics[width=160mm]{figure/ethics_approval.png}
\caption{Notification of ethical approval}
\end{figure}

\section{Correlations for mood measures}
\label{app:mood}

\begin{figure}[h]
\centering
\includegraphics[width=110mm,height=110mm]{figure/PAnas.jpg}
\caption{Correlations between PA scale on PANAS-SF and items `sad' and `depressed'}
\includegraphics[width=110mm,height=110mm]{figure/paNAs.jpg}
\caption{Correlations between NA scale on PANAS-SF and items `anxious' and `worried'}
\end{figure}

\end{document}
